package github.cjcj55.chrispymod.util;

import github.cjcj55.chrispymod.ChrispyMod;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.block.Block;

public class CMBlockTags {
    public static final TagKey<Block> RUBY_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "ruby_ore"));
    public static final TagKey<Block> OPAL_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "opal_ore"));
    public static final TagKey<Block> TANGERINE_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "tangerine_ore"));
    public static final TagKey<Block> COBALT_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "cobalt_ore"));
    public static final TagKey<Block> PARYTH_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "paryth_ore"));
    public static final TagKey<Block> WHITE_DWARF_STAR_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "white_dwarf_star_ore"));
    public static final TagKey<Block> NATURAL_ESSENCE_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "natural_essence_ore"));
    public static final TagKey<Block> EXPERIENCE_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "experience_ore"));
//    public static final TagKey<Block> ALUMINUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "aluminum_ore"));
//    public static final TagKey<Block> ANTIMONY_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "antimony_ore"));
//    public static final TagKey<Block> ARSENIC_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "arsenic_ore"));
//    public static final TagKey<Block> BARIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "barium_ore"));
//    public static final TagKey<Block> BERYLLIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "beryllium_ore"));
//    public static final TagKey<Block> BISMUTH_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "bismuth_ore"));
//    public static final TagKey<Block> BORON_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "boron_ore"));
//    public static final TagKey<Block> CADMIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "cadmium_ore"));
//    public static final TagKey<Block> CALCIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "calcium_ore"));
//    public static final TagKey<Block> CERIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "cerium_ore"));
//    public static final TagKey<Block> CESIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "cesium_ore"));
//    public static final TagKey<Block> CHROMIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "chromium_ore"));
//    public static final TagKey<Block> DYSPROSIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "dysprosium_ore"));
//    public static final TagKey<Block> ERBIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "erbium_ore"));
//    public static final TagKey<Block> EUROPIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "europium_ore"));
//    public static final TagKey<Block> FRANCIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "francium_ore"));
//    public static final TagKey<Block> GADOLINIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "gadolinium_ore"));
//    public static final TagKey<Block> GALLIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "gallium_ore"));
//    public static final TagKey<Block> GERMANIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "germanium_ore"));
//    public static final TagKey<Block> HAFNIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "hafnium_ore"));
//    public static final TagKey<Block> HOLMIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "holmium_ore"));
//    public static final TagKey<Block> INDIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "indium_ore"));
//    public static final TagKey<Block> IRIDIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "iridium_ore"));
//    public static final TagKey<Block> LANTHANUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "lanthanum_ore"));
//    public static final TagKey<Block> LEAD_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "lead_ore"));
//    public static final TagKey<Block> LITHIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "lithium_ore"));
//    public static final TagKey<Block> LUTETIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "lutetium_ore"));
//    public static final TagKey<Block> MAGNESIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "magnesium_ore"));
//    public static final TagKey<Block> MANGANESE_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "manganese_ore"));
//    public static final TagKey<Block> MERCURY_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "mercury_ore"));
//    public static final TagKey<Block> MYTHRIL_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "mythril_ore"));
//    public static final TagKey<Block> MOLYBDENUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "molybdenum_ore"));
//    public static final TagKey<Block> NEODYMIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "neodymium_ore"));
//    public static final TagKey<Block> NICKEL_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "nickel_ore"));
//    public static final TagKey<Block> OSMIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "osmium_ore"));
//    public static final TagKey<Block> PALLADIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "palladium_ore"));
//    public static final TagKey<Block> PLATINUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "platinum_ore"));
//    public static final TagKey<Block> PLUTONIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "plutonium_ore"));
//    public static final TagKey<Block> POLONIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "polonium_ore"));
//    public static final TagKey<Block> POTASSIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "potassium_ore"));
//    public static final TagKey<Block> PRASEODYMIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "praseodymium_ore"));
//    public static final TagKey<Block> PROMETHIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "promethium_ore"));
//    public static final TagKey<Block> RADIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "radium_ore"));
//    public static final TagKey<Block> RHODIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "rhodium_ore"));
//    public static final TagKey<Block> RUTHENIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "ruthenium_ore"));
//    public static final TagKey<Block> SAMARIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "samarium_ore"));
//    public static final TagKey<Block> SCANDIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "scandium_ore"));
//    public static final TagKey<Block> SELENIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "selenium_ore"));
//    public static final TagKey<Block> SILICON_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "silicon_ore"));
//    public static final TagKey<Block> SILVER_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "silver_ore"));
//    public static final TagKey<Block> SODIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "sodium_ore"));
//    public static final TagKey<Block> STRONTIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "strontium_ore"));
//    public static final TagKey<Block> TELLURIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "tellurium_ore"));
//    public static final TagKey<Block> TERBIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "terbium_ore"));
//    public static final TagKey<Block> THALLIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "thallium_ore"));
//    public static final TagKey<Block> THORIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "thorium_ore"));
//    public static final TagKey<Block> THULIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "thulium_ore"));
//    public static final TagKey<Block> TIN_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "tin_ore"));
//    public static final TagKey<Block> TITANIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "titanium_ore"));
//    public static final TagKey<Block> URANIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "uranium_ore"));
//    public static final TagKey<Block> VANADIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "vanadium_ore"));
//    public static final TagKey<Block> VIBRANIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "vibranium_ore"));
//    public static final TagKey<Block> YTTERBIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "ytterbium_ore"));
//    public static final TagKey<Block> YTTRIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "yttrium_ore"));
//    public static final TagKey<Block> ZIRCONIUM_ORE = BlockTags.create(new ResourceLocation(ChrispyMod.MODID, "zirconium_ore"));
}
