package github.cjcj55.chrispymod.registry;

import github.cjcj55.chrispymod.ChrispyMod;
import github.cjcj55.chrispymod.items.*;
import github.cjcj55.chrispymod.items.materials.CMArmorMaterials;
import github.cjcj55.chrispymod.items.materials.CMToolMaterials;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.*;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class CMItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, ChrispyMod.MODID);

    // ITEMS
    public static final RegistryObject<Item> RUBY = ITEMS.register("ruby", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> OPAL = ITEMS.register("opal", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE = ITEMS.register("tangerine", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> COBALT = ITEMS.register("cobalt", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD = ITEMS.register("blue_emerald", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PARYTH = ITEMS.register("paryth", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING = ITEMS.register("lightning", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> FLAME = ITEMS.register("flame", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_INGOT = ITEMS.register("redstone_ingot", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> HELLFIRE = ITEMS.register("hellfire", HellfireItem::new);
    public static final RegistryObject<Item> WHITE_DWARF_STAR = ITEMS.register("white_dwarf_star", FoilItem::new);
    public static final RegistryObject<Item> NATURAL_ESSENCE = ITEMS.register("natural_essence", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> HONEY_STICK = ITEMS.register("honey_stick", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> EDIBLE_EXPERIENCE = ITEMS.register("edible_experience", EdibleExperienceItem::new);
    public static final RegistryObject<Item> ALUMINUM = ITEMS.register("aluminum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_ALUMINUM = ITEMS.register("raw_aluminum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ANTIMONY = ITEMS.register("antimony", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_ANTIMONY = ITEMS.register("raw_antimony", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ARSENIC = ITEMS.register("arsenic", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_ARSENIC = ITEMS.register("raw_arsenic", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BARIUM = ITEMS.register("barium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_BARIUM = ITEMS.register("raw_barium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BERYLLIUM = ITEMS.register("beryllium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_BERYLLIUM = ITEMS.register("raw_beryllium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BISMUTH = ITEMS.register("bismuth", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_BISMUTH = ITEMS.register("raw_bismuth", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> BORON = ITEMS.register("boron", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_BORON = ITEMS.register("raw_boron", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CADMIUM = ITEMS.register("cadmium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_CADMIUM = ITEMS.register("raw_cadmium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CALCIUM = ITEMS.register("calcium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_CALCIUM = ITEMS.register("raw_calcium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CERIUM = ITEMS.register("cerium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_CERIUM = ITEMS.register("raw_cerium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CESIUM = ITEMS.register("cesium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_CESIUM = ITEMS.register("raw_cesium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CHROMIUM = ITEMS.register("chromium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_CHROMIUM = ITEMS.register("raw_chromium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> DYSPROSIUM = ITEMS.register("dysprosium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_DYSPROSIUM = ITEMS.register("raw_dysprosium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ERBIUM = ITEMS.register("erbium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_ERBIUM = ITEMS.register("raw_erbium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> EUROPIUM = ITEMS.register("europium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_EUROPIUM = ITEMS.register("raw_europium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> FRANCIUM = ITEMS.register("francium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_FRANCIUM = ITEMS.register("raw_francium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> GADOLINIUM = ITEMS.register("gadolinium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_GADOLINIUM = ITEMS.register("raw_gadolinium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> GALLIUM = ITEMS.register("gallium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_GALLIUM = ITEMS.register("raw_gallium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> GERMANIUM = ITEMS.register("germanium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_GERMANIUM = ITEMS.register("raw_germanium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> HAFNIUM = ITEMS.register("hafnium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_HAFNIUM = ITEMS.register("raw_hafnium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> HOLMIUM = ITEMS.register("holmium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_HOLMIUM = ITEMS.register("raw_holmium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> INDIUM = ITEMS.register("indium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_INDIUM = ITEMS.register("raw_indium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> IRIDIUM = ITEMS.register("iridium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_IRIDIUM = ITEMS.register("raw_iridium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> LANTHANUM = ITEMS.register("lanthanum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_LANTHANUM = ITEMS.register("raw_lanthanum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> LEAD = ITEMS.register("lead", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_LEAD = ITEMS.register("raw_lead", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> LITHIUM = ITEMS.register("lithium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_LITHIUM = ITEMS.register("raw_lithium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> LUTETIUM = ITEMS.register("lutetium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_LUTETIUM = ITEMS.register("raw_lutetium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> MAGNESIUM = ITEMS.register("magnesium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_MAGNESIUM = ITEMS.register("raw_magnesium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> MANGANESE = ITEMS.register("manganese", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_MANGANESE = ITEMS.register("raw_manganese", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> MERCURY = ITEMS.register("mercury", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_MERCURY = ITEMS.register("raw_mercury", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> MYTHRIL = ITEMS.register("mythril", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_MYTHRIL = ITEMS.register("raw_mythril", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> MOLYBDENUM = ITEMS.register("molybdenum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_MOLYBDENUM = ITEMS.register("raw_molybdenum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> NEODYMIUM = ITEMS.register("neodymium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_NEODYMIUM = ITEMS.register("raw_neodymium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> NICKEL = ITEMS.register("nickel", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_NICKEL = ITEMS.register("raw_nickel", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> OSMIUM = ITEMS.register("osmium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_OSMIUM = ITEMS.register("raw_osmium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PALLADIUM = ITEMS.register("palladium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_PALLADIUM = ITEMS.register("raw_palladium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PLATINUM = ITEMS.register("platinum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_PLATINUM = ITEMS.register("raw_platinum", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PLUTONIUM = ITEMS.register("plutonium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_PLUTONIUM = ITEMS.register("raw_plutonium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> POLONIUM = ITEMS.register("polonium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_POLONIUM = ITEMS.register("raw_polonium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> POTASSIUM = ITEMS.register("potassium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_POTASSIUM = ITEMS.register("raw_potassium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PRASEODYMIUM = ITEMS.register("praseodymium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_PRASEODYMIUM = ITEMS.register("raw_praseodymium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> PROMETHIUM = ITEMS.register("promethium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_PROMETHIUM = ITEMS.register("raw_promethium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RADIUM = ITEMS.register("radium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_RADIUM = ITEMS.register("raw_radium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RHODIUM = ITEMS.register("rhodium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_RHODIUM = ITEMS.register("raw_rhodium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RUTHENIUM = ITEMS.register("ruthenium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_RUTHENIUM = ITEMS.register("raw_ruthenium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SAMARIUM = ITEMS.register("samarium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_SAMARIUM = ITEMS.register("raw_samarium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SCANDIUM = ITEMS.register("scandium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_SCANDIUM = ITEMS.register("raw_scandium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SELENIUM = ITEMS.register("selenium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_SELENIUM = ITEMS.register("raw_selenium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SILICON = ITEMS.register("silicon", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_SILICON = ITEMS.register("raw_silicon", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SILVER = ITEMS.register("silver", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_SILVER = ITEMS.register("raw_silver", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> SODIUM = ITEMS.register("sodium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_SODIUM = ITEMS.register("raw_sodium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> STRONTIUM = ITEMS.register("strontium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_STRONTIUM = ITEMS.register("raw_strontium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> TELLURIUM = ITEMS.register("tellurium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_TELLURIUM = ITEMS.register("raw_tellurium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> TERBIUM = ITEMS.register("terbium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_TERBIUM = ITEMS.register("raw_terbium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> THALLIUM = ITEMS.register("thallium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_THALLIUM = ITEMS.register("raw_thallium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> THORIUM = ITEMS.register("thorium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_THORIUM = ITEMS.register("raw_thorium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> THULIUM = ITEMS.register("thulium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_THULIUM = ITEMS.register("raw_thulium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> TIN = ITEMS.register("tin", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_TIN = ITEMS.register("raw_tin", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> TITANIUM = ITEMS.register("titanium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_TITANIUM = ITEMS.register("raw_titanium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> URANIUM = ITEMS.register("uranium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_URANIUM = ITEMS.register("raw_uranium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> VANADIUM = ITEMS.register("vanadium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_VANADIUM = ITEMS.register("raw_vanadium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> VIBRANIUM = ITEMS.register("vibranium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_VIBRANIUM = ITEMS.register("raw_vibranium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> YTTERBIUM = ITEMS.register("ytterbium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_YTTERBIUM = ITEMS.register("raw_ytterbium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> YTTRIUM = ITEMS.register("yttrium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_YTTRIUM = ITEMS.register("raw_yttrium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ZIRCONIUM = ITEMS.register("zirconium", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> RAW_ZIRCONIUM = ITEMS.register("raw_zirconium", () -> new Item(new Item.Properties()));

    // TOOLS
    public static final RegistryObject<Item> RUBY_SWORD = ITEMS.register("ruby_sword", () -> new SwordItem(CMToolMaterials.RUBY, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_SHOVEL = ITEMS.register("ruby_shovel", () -> new ShovelItem(CMToolMaterials.RUBY, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_PICKAXE = ITEMS.register("ruby_pickaxe", () -> new PickaxeItem(CMToolMaterials.RUBY, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_AXE = ITEMS.register("ruby_axe", () -> new AxeItem(CMToolMaterials.RUBY, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_HOE = ITEMS.register("ruby_hoe", () -> new HoeItem(CMToolMaterials.RUBY, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_HELMET = ITEMS.register("ruby_helmet", () -> new ArmorItem(CMArmorMaterials.RUBY, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_CHESTPLATE = ITEMS.register("ruby_chestplate", () -> new ArmorItem(CMArmorMaterials.RUBY, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_LEGGINGS = ITEMS.register("ruby_leggings", () -> new ArmorItem(CMArmorMaterials.RUBY, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> RUBY_BOOTS = ITEMS.register("ruby_boots", () -> new ArmorItem(CMArmorMaterials.RUBY, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> OPAL_SWORD = ITEMS.register("opal_sword", () -> new SwordItem(CMToolMaterials.OPAL, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_SHOVEL = ITEMS.register("opal_shovel", () -> new ShovelItem(CMToolMaterials.OPAL, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_PICKAXE = ITEMS.register("opal_pickaxe", () -> new PickaxeItem(CMToolMaterials.OPAL, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_AXE = ITEMS.register("opal_axe", () -> new AxeItem(CMToolMaterials.OPAL, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_HOE = ITEMS.register("opal_hoe", () -> new HoeItem(CMToolMaterials.OPAL, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_HELMET = ITEMS.register("opal_helmet", () -> new ArmorItem(CMArmorMaterials.OPAL, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_CHESTPLATE = ITEMS.register("opal_chestplate", () -> new ArmorItem(CMArmorMaterials.OPAL, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_LEGGINGS = ITEMS.register("opal_leggings", () -> new ArmorItem(CMArmorMaterials.OPAL, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> OPAL_BOOTS = ITEMS.register("opal_boots", () -> new ArmorItem(CMArmorMaterials.OPAL, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> TANGERINE_SWORD = ITEMS.register("tangerine_sword", () -> new SwordItem(CMToolMaterials.TANGERINE, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_SHOVEL = ITEMS.register("tangerine_shovel", () -> new ShovelItem(CMToolMaterials.TANGERINE, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_PICKAXE = ITEMS.register("tangerine_pickaxe", () -> new PickaxeItem(CMToolMaterials.TANGERINE, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_AXE = ITEMS.register("tangerine_axe", () -> new AxeItem(CMToolMaterials.TANGERINE, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_HOE = ITEMS.register("tangerine_hoe", () -> new HoeItem(CMToolMaterials.TANGERINE, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_HELMET = ITEMS.register("tangerine_helmet", () -> new ArmorItem(CMArmorMaterials.TANGERINE, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_CHESTPLATE = ITEMS.register("tangerine_chestplate", () -> new ArmorItem(CMArmorMaterials.TANGERINE, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_LEGGINGS = ITEMS.register("tangerine_leggings", () -> new ArmorItem(CMArmorMaterials.TANGERINE, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> TANGERINE_BOOTS = ITEMS.register("tangerine_boots", () -> new ArmorItem(CMArmorMaterials.TANGERINE, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> COBALT_SWORD = ITEMS.register("cobalt_sword", () -> new SwordItem(CMToolMaterials.COBALT, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_SHOVEL = ITEMS.register("cobalt_shovel", () -> new ShovelItem(CMToolMaterials.COBALT, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_PICKAXE = ITEMS.register("cobalt_pickaxe", () -> new PickaxeItem(CMToolMaterials.COBALT, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_AXE = ITEMS.register("cobalt_axe", () -> new AxeItem(CMToolMaterials.COBALT, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_HOE = ITEMS.register("cobalt_hoe", () -> new HoeItem(CMToolMaterials.COBALT, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_HELMET = ITEMS.register("cobalt_helmet", () -> new ArmorItem(CMArmorMaterials.COBALT, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_CHESTPLATE = ITEMS.register("cobalt_chestplate", () -> new ArmorItem(CMArmorMaterials.COBALT, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_LEGGINGS = ITEMS.register("cobalt_leggings", () -> new ArmorItem(CMArmorMaterials.COBALT, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> COBALT_BOOTS = ITEMS.register("cobalt_boots", () -> new ArmorItem(CMArmorMaterials.COBALT, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> BLUE_EMERALD_SWORD = ITEMS.register("blue_emerald_sword", () -> new SwordItem(CMToolMaterials.BLUE_EMERALD, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_SHOVEL = ITEMS.register("blue_emerald_shovel", () -> new ShovelItem(CMToolMaterials.BLUE_EMERALD, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_PICKAXE = ITEMS.register("blue_emerald_pickaxe", () -> new PickaxeItem(CMToolMaterials.BLUE_EMERALD, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_AXE = ITEMS.register("blue_emerald_axe", () -> new AxeItem(CMToolMaterials.BLUE_EMERALD, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_HOE = ITEMS.register("blue_emerald_hoe", () -> new HoeItem(CMToolMaterials.BLUE_EMERALD, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_HELMET = ITEMS.register("blue_emerald_helmet", () -> new ArmorItem(CMArmorMaterials.BLUE_EMERALD, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_CHESTPLATE = ITEMS.register("blue_emerald_chestplate", () -> new ArmorItem(CMArmorMaterials.BLUE_EMERALD, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_LEGGINGS = ITEMS.register("blue_emerald_leggings", () -> new ArmorItem(CMArmorMaterials.BLUE_EMERALD, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> BLUE_EMERALD_BOOTS = ITEMS.register("blue_emerald_boots", () -> new ArmorItem(CMArmorMaterials.BLUE_EMERALD, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> PARYTH_SWORD = ITEMS.register("paryth_sword", () -> new SwordItem(CMToolMaterials.PARYTH, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_SHOVEL = ITEMS.register("paryth_shovel", () -> new ShovelItem(CMToolMaterials.PARYTH, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_PICKAXE = ITEMS.register("paryth_pickaxe", () -> new PickaxeItem(CMToolMaterials.PARYTH, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_AXE = ITEMS.register("paryth_axe", () -> new AxeItem(CMToolMaterials.PARYTH, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_HOE = ITEMS.register("paryth_hoe", () -> new HoeItem(CMToolMaterials.PARYTH, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_HELMET = ITEMS.register("paryth_helmet", () -> new ArmorItem(CMArmorMaterials.PARYTH, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_CHESTPLATE = ITEMS.register("paryth_chestplate", () -> new ArmorItem(CMArmorMaterials.PARYTH, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_LEGGINGS = ITEMS.register("paryth_leggings", () -> new ArmorItem(CMArmorMaterials.PARYTH, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> PARYTH_BOOTS = ITEMS.register("paryth_boots", () -> new ArmorItem(CMArmorMaterials.PARYTH, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> LIGHTNING_SWORD = ITEMS.register("lightning_sword", () -> new LightningSwordItem(CMToolMaterials.LIGHTNING, 3, -2.4F));
    public static final RegistryObject<Item> LIGHTNING_SHOVEL = ITEMS.register("lightning_shovel", () -> new ShovelItem(CMToolMaterials.LIGHTNING, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_PICKAXE = ITEMS.register("lightning_pickaxe", () -> new PickaxeItem(CMToolMaterials.LIGHTNING, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_AXE = ITEMS.register("lightning_axe", () -> new AxeItem(CMToolMaterials.LIGHTNING, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_HOE = ITEMS.register("lightning_hoe", () -> new HoeItem(CMToolMaterials.LIGHTNING, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_HELMET = ITEMS.register("lightning_helmet", () -> new ArmorItem(CMArmorMaterials.LIGHTNING, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_CHESTPLATE = ITEMS.register("lightning_chestplate", () -> new ArmorItem(CMArmorMaterials.LIGHTNING, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_LEGGINGS = ITEMS.register("lightning_leggings", () -> new ArmorItem(CMArmorMaterials.LIGHTNING, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> LIGHTNING_BOOTS = ITEMS.register("lightning_boots", () -> new ArmorItem(CMArmorMaterials.LIGHTNING, ArmorItem.Type.BOOTS, new Item.Properties()));
    // Lightning Wand
    public static final RegistryObject<Item> LIGHTNING_WAND = ITEMS.register("lightning_wand", LightningWandItem::new);
    public static final RegistryObject<Item> FLAME_WAND = ITEMS.register("flame_wand", FlameWandItem::new);


    public static final RegistryObject<Item> FLAME_SWORD = ITEMS.register("flame_sword", () -> new FlameSwordItem(CMToolMaterials.FLAME, 3, -2.4F));
    public static final RegistryObject<Item> FLAME_SHOVEL = ITEMS.register("flame_shovel", () -> new ShovelItem(CMToolMaterials.FLAME, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> FLAME_PICKAXE = ITEMS.register("flame_pickaxe", () -> new PickaxeItem(CMToolMaterials.FLAME, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> FLAME_AXE = ITEMS.register("flame_axe", () -> new AxeItem(CMToolMaterials.FLAME, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> FLAME_HOE = ITEMS.register("flame_hoe", () -> new HoeItem(CMToolMaterials.FLAME, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> FLAME_HELMET = ITEMS.register("flame_helmet", () -> new FlameArmorItem(CMArmorMaterials.FLAME, ArmorItem.Type.HELMET));
    public static final RegistryObject<Item> FLAME_CHESTPLATE = ITEMS.register("flame_chestplate", () -> new FlameArmorItem(CMArmorMaterials.FLAME, ArmorItem.Type.CHESTPLATE));
    public static final RegistryObject<Item> FLAME_LEGGINGS = ITEMS.register("flame_leggings", () -> new FlameArmorItem(CMArmorMaterials.FLAME, ArmorItem.Type.LEGGINGS));
    public static final RegistryObject<Item> FLAME_BOOTS = ITEMS.register("flame_boots", () -> new FlameArmorItem(CMArmorMaterials.FLAME, ArmorItem.Type.BOOTS));

    public static final RegistryObject<Item> REDSTONE_SWORD = ITEMS.register("redstone_sword", () -> new SwordItem(CMToolMaterials.REDSTONE, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_SHOVEL = ITEMS.register("redstone_shovel", () -> new ShovelItem(CMToolMaterials.REDSTONE, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_PICKAXE = ITEMS.register("redstone_pickaxe", () -> new PickaxeItem(CMToolMaterials.REDSTONE, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_AXE = ITEMS.register("redstone_axe", () -> new AxeItem(CMToolMaterials.REDSTONE, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_HOE = ITEMS.register("redstone_hoe", () -> new HoeItem(CMToolMaterials.REDSTONE, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_HELMET = ITEMS.register("redstone_helmet", () -> new ArmorItem(CMArmorMaterials.REDSTONE, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_CHESTPLATE = ITEMS.register("redstone_chestplate", () -> new ArmorItem(CMArmorMaterials.REDSTONE, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_LEGGINGS = ITEMS.register("redstone_leggings", () -> new ArmorItem(CMArmorMaterials.REDSTONE, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> REDSTONE_BOOTS = ITEMS.register("redstone_boots", () -> new ArmorItem(CMArmorMaterials.REDSTONE, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> EMERALD_SWORD = ITEMS.register("emerald_sword", () -> new SwordItem(CMToolMaterials.EMERALD, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_SHOVEL = ITEMS.register("emerald_shovel", () -> new ShovelItem(CMToolMaterials.EMERALD, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_PICKAXE = ITEMS.register("emerald_pickaxe", () -> new PickaxeItem(CMToolMaterials.EMERALD, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_AXE = ITEMS.register("emerald_axe", () -> new AxeItem(CMToolMaterials.EMERALD, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_HOE = ITEMS.register("emerald_hoe", () -> new HoeItem(CMToolMaterials.EMERALD, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_HELMET = ITEMS.register("emerald_helmet", () -> new ArmorItem(CMArmorMaterials.EMERALD, ArmorItem.Type.HELMET, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_CHESTPLATE = ITEMS.register("emerald_chestplate", () -> new ArmorItem(CMArmorMaterials.EMERALD, ArmorItem.Type.CHESTPLATE, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_LEGGINGS = ITEMS.register("emerald_leggings", () -> new ArmorItem(CMArmorMaterials.EMERALD, ArmorItem.Type.LEGGINGS, new Item.Properties()));
    public static final RegistryObject<Item> EMERALD_BOOTS = ITEMS.register("emerald_boots", () -> new ArmorItem(CMArmorMaterials.EMERALD, ArmorItem.Type.BOOTS, new Item.Properties()));

    public static final RegistryObject<Item> HONEY_SWORD = ITEMS.register("honey_sword", () -> new SwordItem(CMToolMaterials.HONEY, 3, -2.4F, new Item.Properties()));
    public static final RegistryObject<Item> HONEY_SHOVEL = ITEMS.register("honey_shovel", () -> new ShovelItem(CMToolMaterials.HONEY, 1.5F, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> HONEY_PICKAXE = ITEMS.register("honey_pickaxe", () -> new PickaxeItem(CMToolMaterials.HONEY, 1, -2.8F, new Item.Properties()));
    public static final RegistryObject<Item> HONEY_AXE = ITEMS.register("honey_axe", () -> new AxeItem(CMToolMaterials.HONEY, 6.0F, -3.2F, new Item.Properties()));
    public static final RegistryObject<Item> HONEY_HOE = ITEMS.register("honey_hoe", () -> new HoeItem(CMToolMaterials.HONEY, 0, -3.0F, new Item.Properties()));
    public static final RegistryObject<Item> HONEY_HELMET = ITEMS.register("honey_helmet", () -> new HoneyArmorItem(CMArmorMaterials.HONEY, ArmorItem.Type.HELMET));
    public static final RegistryObject<Item> HONEY_CHESTPLATE = ITEMS.register("honey_chestplate", () -> new HoneyArmorItem(CMArmorMaterials.HONEY, ArmorItem.Type.CHESTPLATE));
    public static final RegistryObject<Item> HONEY_LEGGINGS = ITEMS.register("honey_leggings", () -> new HoneyArmorItem(CMArmorMaterials.HONEY, ArmorItem.Type.LEGGINGS));
    public static final RegistryObject<Item> HONEY_BOOTS = ITEMS.register("honey_boots", () -> new HoneyArmorItem(CMArmorMaterials.HONEY, ArmorItem.Type.BOOTS));

    public static final RegistryObject<Item> WHITE_DWARF_STAR_HELMET = ITEMS.register("white_dwarf_star_helmet", () -> new WhiteDwarfStarArmorItem(CMArmorMaterials.WHITE_DWARF_STAR, ArmorItem.Type.HELMET));
    public static final RegistryObject<Item> WHITE_DWARF_STAR_CHESTPLATE = ITEMS.register("white_dwarf_star_chestplate", () -> new WhiteDwarfStarArmorItem(CMArmorMaterials.WHITE_DWARF_STAR, ArmorItem.Type.CHESTPLATE));
    public static final RegistryObject<Item> WHITE_DWARF_STAR_LEGGINGS = ITEMS.register("white_dwarf_star_leggings", () -> new WhiteDwarfStarArmorItem(CMArmorMaterials.WHITE_DWARF_STAR, ArmorItem.Type.LEGGINGS));
    public static final RegistryObject<Item> WHITE_DWARF_STAR_BOOTS = ITEMS.register("white_dwarf_star_boots", () -> new WhiteDwarfStarArmorItem(CMArmorMaterials.WHITE_DWARF_STAR, ArmorItem.Type.BOOTS));

    // FOOD
    public static final RegistryObject<Item> BLACK_CANDY_CANE = ITEMS.register("black_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.BLACK_CANDY_CANE)));
    public static final RegistryObject<Item> BLUE_CANDY_CANE = ITEMS.register("blue_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.BLUE_CANDY_CANE)));
    public static final RegistryObject<Item> BROWN_CANDY_CANE = ITEMS.register("brown_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.BROWN_CANDY_CANE)));
    public static final RegistryObject<Item> CYAN_CANDY_CANE = ITEMS.register("cyan_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.CYAN_CANDY_CANE)));
    public static final RegistryObject<Item> GRAY_CANDY_CANE = ITEMS.register("gray_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.GRAY_CANDY_CANE)));
    public static final RegistryObject<Item> GREEN_CANDY_CANE = ITEMS.register("green_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.GREEN_CANDY_CANE)));
    public static final RegistryObject<Item> LIGHT_BLUE_CANDY_CANE = ITEMS.register("light_blue_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.LIGHT_BLUE_CANDY_CANE)));
    public static final RegistryObject<Item> LIGHT_GRAY_CANDY_CANE = ITEMS.register("light_gray_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.LIGHT_GRAY_CANDY_CANE)));
    public static final RegistryObject<Item> LIME_CANDY_CANE = ITEMS.register("lime_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.LIME_CANDY_CANE)));
    public static final RegistryObject<Item> MAGENTA_CANDY_CANE = ITEMS.register("magenta_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.MAGENTA_CANDY_CANE)));
    public static final RegistryObject<Item> ORANGE_CANDY_CANE = ITEMS.register("orange_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.ORANGE_CANDY_CANE)));
    public static final RegistryObject<Item> PINK_CANDY_CANE = ITEMS.register("pink_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.PINK_CANDY_CANE)));
    public static final RegistryObject<Item> PURPLE_CANDY_CANE = ITEMS.register("purple_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.PURPLE_CANDY_CANE)));
    public static final RegistryObject<Item> RED_CANDY_CANE = ITEMS.register("red_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.RED_CANDY_CANE)));
    public static final RegistryObject<Item> WHITE_CANDY_CANE = ITEMS.register("white_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.WHITE_CANDY_CANE)));
    public static final RegistryObject<Item> YELLOW_CANDY_CANE = ITEMS.register("yellow_candy_cane", () -> new Item(new Item.Properties().food(CMFoodProperties.YELLOW_CANDY_CANE)));
    public static final RegistryObject<Item> COOKED_CARROT = ITEMS.register("cooked_carrot", () -> new Item(new Item.Properties().food(CMFoodProperties.COOKED_CARROT)));

    public static final RegistryObject<Item> STRAWBERRY = ITEMS.register("strawberry", () -> new BerryItem(CMBlocks.STRAWBERRY_BUSH.get(), CMFoodProperties.STRAWBERRY));
    public static final RegistryObject<Item> BLUEBERRY = ITEMS.register("blueberry", () -> new BerryItem(CMBlocks.BLUEBERRY_BUSH.get(), CMFoodProperties.BLUEBERRY));
    public static final RegistryObject<Item> LOGANBERRY = ITEMS.register("loganberry", () -> new BerryItem(CMBlocks.LOGANBERRY_BUSH.get(), CMFoodProperties.LOGANBERRY));
    public static final RegistryObject<Item> RED_RASPBERRY = ITEMS.register("red_raspberry", () -> new BerryItem(CMBlocks.RED_RASPBERRY_BUSH.get(), CMFoodProperties.RED_RASPBERRY));
    public static final RegistryObject<Item> BLACK_RASPBERRY = ITEMS.register("black_raspberry", () -> new BerryItem(CMBlocks.BLACK_RASPBERRY_BUSH.get(), CMFoodProperties.BLACK_RASPBERRY));
    public static final RegistryObject<Item> GOLDEN_RASPBERRY = ITEMS.register("golden_raspberry", () -> new BerryItem(CMBlocks.GOLDEN_RASPBERRY_BUSH.get(), CMFoodProperties.GOLDEN_RASPBERRY));
    public static final RegistryObject<Item> WHITE_RASPBERRY = ITEMS.register("white_raspberry", () -> new BerryItem(CMBlocks.WHITE_RASPBERRY_BUSH.get(), CMFoodProperties.WHITE_RASPBERRY));
    public static final RegistryObject<Item> MARIONBERRY = ITEMS.register("marionberry", () -> new BerryItem(CMBlocks.MARIONBERRY_BUSH.get(), CMFoodProperties.MARIONBERRY));
    public static final RegistryObject<Item> BLACKCURRANT = ITEMS.register("blackcurrant", () -> new BerryItem(CMBlocks.BLACKCURRANT_BUSH.get(), CMFoodProperties.BLACKCURRANT));
    public static final RegistryObject<Item> REDCURRANT = ITEMS.register("redcurrant", () -> new BerryItem(CMBlocks.REDCURRANT_BUSH.get(), CMFoodProperties.REDCURRANT));
    public static final RegistryObject<Item> HUCKLEBERRY = ITEMS.register("huckleberry", () -> new BerryItem(CMBlocks.HUCKLEBERRY_BUSH.get(), CMFoodProperties.HUCKLEBERRY));
    public static final RegistryObject<Item> WINEBERRY = ITEMS.register("wineberry", () -> new BerryItem(CMBlocks.WINEBERRY_BUSH.get(), CMFoodProperties.WINEBERRY));
    public static final RegistryObject<Item> ELDERBERRY = ITEMS.register("elderberry", () -> new BerryItem(CMBlocks.ELDERBERRY_BUSH.get(), CMFoodProperties.ELDERBERRY));
    public static final RegistryObject<Item> BLACKBERRY = ITEMS.register("blackberry", () -> new BerryItem(CMBlocks.BLACKBERRY_BUSH.get(), CMFoodProperties.BLACKBERRY));
    public static final RegistryObject<Item> BOYSENBERRY = ITEMS.register("boysenberry", () -> new BerryItem(CMBlocks.BOYSENBERRY_BUSH.get(), CMFoodProperties.BOYSENBERRY));
    public static final RegistryObject<Item> GROUND_CHERRY = ITEMS.register("ground_cherry", () -> new BerryItem(CMBlocks.GROUND_CHERRY_BUSH.get(), CMFoodProperties.GROUND_CHERRY));
    public static final RegistryObject<Item> ARONIA_BERRY = ITEMS.register("aronia_berry", () -> new BerryItem(CMBlocks.ARONIA_BERRY_BUSH.get(), CMFoodProperties.ARONIA_BERRY));
    public static final RegistryObject<Item> SERVICEBERRY = ITEMS.register("serviceberry", () -> new BerryItem(CMBlocks.SERVICEBERRY_BUSH.get(), CMFoodProperties.SERVICEBERRY));
    public static final RegistryObject<Item> WONDERBERRY = ITEMS.register("wonderberry", () -> new BerryItem(CMBlocks.WONDERBERRY_BUSH.get(), CMFoodProperties.WONDERBERRY));
    public static final RegistryObject<Item> MULBERRY = ITEMS.register("mulberry", () -> new BerryItem(CMBlocks.MULBERRY_BUSH.get(), CMFoodProperties.MULBERRY));
    public static final RegistryObject<Item> LINGONBERRY = ITEMS.register("lingonberry", () -> new BerryItem(CMBlocks.LINGONBERRY_BUSH.get(), CMFoodProperties.LINGONBERRY));
    public static final RegistryObject<Item> CRANBERRY = ITEMS.register("cranberry", () -> new BerryItem(CMBlocks.CRANBERRY_BUSH.get(), CMFoodProperties.CRANBERRY));
    public static final RegistryObject<Item> DEWBERRY = ITEMS.register("dewberry", () -> new BerryItem(CMBlocks.DEWBERRY_BUSH.get(), CMFoodProperties.DEWBERRY));
    public static final RegistryObject<Item> THIMBLEBERRY = ITEMS.register("thimbleberry", () -> new BerryItem(CMBlocks.THIMBLEBERRY_BUSH.get(), CMFoodProperties.THIMBLEBERRY));
    public static final RegistryObject<Item> GOOSEBERRY = ITEMS.register("gooseberry", () -> new BerryItem(CMBlocks.GOOSEBERRY_BUSH.get(), CMFoodProperties.GOOSEBERRY));
    public static final RegistryObject<Item> CHOKEBERRY = ITEMS.register("chokeberry", () -> new BerryItem(CMBlocks.CHOKEBERRY_BUSH.get(), CMFoodProperties.CHOKEBERRY));
    public static final RegistryObject<Item> OLALLIEBERRY = ITEMS.register("olallieberry", () -> new BerryItem(CMBlocks.OLALLIEBERRY_BUSH.get(), CMFoodProperties.OLALLIEBERRY));
    public static final RegistryObject<Item> ACEROLA_CHERRY = ITEMS.register("acerola_cherry", () -> new BerryItem(CMBlocks.ACEROLA_CHERRY_BUSH.get(), CMFoodProperties.ACEROLA_CHERRY));
    public static final RegistryObject<Item> BARBERRY = ITEMS.register("barberry", () -> new BerryItem(CMBlocks.BARBERRY_BUSH.get(), CMFoodProperties.BARBERRY));
    public static final RegistryObject<Item> BAYBERRY = ITEMS.register("bayberry", () -> new BerryItem(CMBlocks.BAYBERRY_BUSH.get(), CMFoodProperties.BAYBERRY));
    public static final RegistryObject<Item> GOGI_BERRY = ITEMS.register("gogi_berry", () -> new BerryItem(CMBlocks.GOGI_BERRY_BUSH.get(), CMFoodProperties.GOGI_BERRY));

    public static final RegistryObject<Item> STRAWBERRY_JAM = ITEMS.register("strawberry_jam", () -> new BerryJamItem(CMFoodProperties.STRAWBERRY_JAM));
    public static final RegistryObject<Item> BLUEBERRY_JAM = ITEMS.register("blueberry_jam", () -> new BerryJamItem(CMFoodProperties.BLUEBERRY_JAM));
    public static final RegistryObject<Item> LOGANBERRY_JAM = ITEMS.register("loganberry_jam", () -> new BerryJamItem(CMFoodProperties.LOGANBERRY_JAM));
    public static final RegistryObject<Item> RED_RASPBERRY_JAM = ITEMS.register("red_raspberry_jam", () -> new BerryJamItem(CMFoodProperties.RED_RASPBERRY_JAM));
    public static final RegistryObject<Item> BLACK_RASPBERRY_JAM = ITEMS.register("black_raspberry_jam", () -> new BerryJamItem(CMFoodProperties.BLACK_RASPBERRY_JAM));
    public static final RegistryObject<Item> GOLDEN_RASPBERRY_JAM = ITEMS.register("golden_raspberry_jam", () -> new BerryJamItem(CMFoodProperties.GOLDEN_RASPBERRY_JAM));
    public static final RegistryObject<Item> WHITE_RASPBERRY_JAM = ITEMS.register("white_raspberry_jam", () -> new BerryJamItem(CMFoodProperties.WHITE_RASPBERRY_JAM));
    public static final RegistryObject<Item> MARIONBERRY_JAM = ITEMS.register("marionberry_jam", () -> new BerryJamItem(CMFoodProperties.MARIONBERRY_JAM));
    public static final RegistryObject<Item> BLACKCURRANT_JAM = ITEMS.register("blackcurrant_jam", () -> new BerryJamItem(CMFoodProperties.BLACKCURRANT_JAM));
    public static final RegistryObject<Item> REDCURRANT_JAM = ITEMS.register("redcurrant_jam", () -> new BerryJamItem(CMFoodProperties.REDCURRANT_JAM));
    public static final RegistryObject<Item> HUCKLEBERRY_JAM = ITEMS.register("huckleberry_jam", () -> new BerryJamItem(CMFoodProperties.HUCKLEBERRY_JAM));
    public static final RegistryObject<Item> WINEBERRY_JAM = ITEMS.register("wineberry_jam", () -> new BerryJamItem(CMFoodProperties.WINEBERRY_JAM));
    public static final RegistryObject<Item> ELDERBERRY_JAM = ITEMS.register("elderberry_jam", () -> new BerryJamItem(CMFoodProperties.ELDERBERRY_JAM));
    public static final RegistryObject<Item> BLACKBERRY_JAM = ITEMS.register("blackberry_jam", () -> new BerryJamItem(CMFoodProperties.BLACKBERRY_JAM));
    public static final RegistryObject<Item> BOYSENBERRY_JAM = ITEMS.register("boysenberry_jam", () -> new BerryJamItem(CMFoodProperties.BOYSENBERRY_JAM));
    public static final RegistryObject<Item> GROUND_CHERRY_JAM = ITEMS.register("ground_cherry_jam", () -> new BerryJamItem(CMFoodProperties.GROUND_CHERRY_JAM));
    public static final RegistryObject<Item> ARONIA_BERRY_JAM = ITEMS.register("aronia_berry_jam", () -> new BerryJamItem(CMFoodProperties.ARONIA_BERRY_JAM));
    public static final RegistryObject<Item> SERVICEBERRY_JAM = ITEMS.register("serviceberry_jam", () -> new BerryJamItem(CMFoodProperties.SERVICEBERRY_JAM));
    public static final RegistryObject<Item> WONDERBERRY_JAM = ITEMS.register("wonderberry_jam", () -> new BerryJamItem(CMFoodProperties.WONDERBERRY_JAM));
    public static final RegistryObject<Item> MULBERRY_JAM = ITEMS.register("mulberry_jam", () -> new BerryJamItem(CMFoodProperties.MULBERRY_JAM));
    public static final RegistryObject<Item> LINGONBERRY_JAM = ITEMS.register("lingonberry_jam", () -> new BerryJamItem(CMFoodProperties.LINGONBERRY_JAM));
    public static final RegistryObject<Item> CRANBERRY_JAM = ITEMS.register("cranberry_jam", () -> new BerryJamItem(CMFoodProperties.CRANBERRY_JAM));
    public static final RegistryObject<Item> DEWBERRY_JAM = ITEMS.register("dewberry_jam", () -> new BerryJamItem(CMFoodProperties.DEWBERRY_JAM));
    public static final RegistryObject<Item> THIMBLEBERRY_JAM = ITEMS.register("thimbleberry_jam", () -> new BerryJamItem(CMFoodProperties.THIMBLEBERRY_JAM));
    public static final RegistryObject<Item> GOOSEBERRY_JAM = ITEMS.register("gooseberry_jam", () -> new BerryJamItem(CMFoodProperties.GOOSEBERRY_JAM));
    public static final RegistryObject<Item> CHOKEBERRY_JAM = ITEMS.register("chokeberry_jam", () -> new BerryJamItem(CMFoodProperties.CHOKEBERRY_JAM));
    public static final RegistryObject<Item> OLALLIEBERRY_JAM = ITEMS.register("olallieberry_jam", () -> new BerryJamItem(CMFoodProperties.OLALLIEBERRY_JAM));
    public static final RegistryObject<Item> ACEROLA_CHERRY_JAM = ITEMS.register("acerola_cherry_jam", () -> new BerryJamItem(CMFoodProperties.ACEROLA_CHERRY_JAM));
    public static final RegistryObject<Item> BARBERRY_JAM = ITEMS.register("barberry_jam", () -> new BerryJamItem(CMFoodProperties.BARBERRY_JAM));
    public static final RegistryObject<Item> BAYBERRY_JAM = ITEMS.register("bayberry_jam", () -> new BerryJamItem(CMFoodProperties.BAYBERRY_JAM));
    public static final RegistryObject<Item> GOGI_BERRY_JAM = ITEMS.register("gogi_berry_jam", () -> new BerryJamItem(CMFoodProperties.GOGI_BERRY_JAM));

    public static final RegistryObject<Item> MASON_JAR = ITEMS.register("mason_jar", () -> new Item(new Item.Properties()));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }
}
