package io.github.cjcj55.chrispymod.core.world.feature;

import io.github.cjcj55.chrispymod.core.init.BlockInit;
import net.minecraft.data.worldgen.features.FeatureUtils;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SweetBerryBushBlock;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.configurations.SimpleBlockConfiguration;
import net.minecraft.world.level.levelgen.feature.stateproviders.BlockStateProvider;

import java.util.List;

public class CMVegetationFeatures {
    public static final ConfiguredFeature<?, ?> PATCH_STRAWBERRY_BUSH = FeatureUtils.register("patch_strawberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.STRAWBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BLUEBERRY_BUSH = FeatureUtils.register("patch_blueberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BLUEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_LOGANBERRY_BUSH = FeatureUtils.register("patch_loganberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.LOGANBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_RED_RASPBERRY_BUSH = FeatureUtils.register("patch_red_raspberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.RED_RASPBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BLACK_RASPBERRY_BUSH = FeatureUtils.register("patch_black_raspberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BLACK_RASPBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_GOLDEN_RASPBERRY_BUSH = FeatureUtils.register("patch_golden_raspberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.GOLDEN_RASPBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_WHITE_RASPBERRY_BUSH = FeatureUtils.register("patch_white_raspberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.WHITE_RASPBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_MARIONBERRY_BUSH = FeatureUtils.register("patch_marionberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.MARIONBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BLACKCURRANT_BUSH = FeatureUtils.register("patch_blackcurrant_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BLACKCURRANT_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_REDCURRANT_BUSH = FeatureUtils.register("patch_redcurrant_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.REDCURRANT_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_HUCKLEBERRY_BUSH = FeatureUtils.register("patch_huckleberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.HUCKLEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_WINEBERRY_BUSH = FeatureUtils.register("patch_wineberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.WINEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_ELDERBERRY_BUSH = FeatureUtils.register("patch_elderberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.ELDERBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BLACKBERRY_BUSH = FeatureUtils.register("patch_blackberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BLACKBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BOYSENBERRY_BUSH = FeatureUtils.register("patch_boysenberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BOYSENBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_GROUND_CHERRY_BUSH = FeatureUtils.register("patch_ground_cherry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.GROUND_CHERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_ARONIA_BERRY_BUSH = FeatureUtils.register("patch_aronia_berry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.ARONIA_BERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_SERVICEBERRY_BUSH = FeatureUtils.register("patch_serviceberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.SERVICEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_WONDERBERRY_BUSH = FeatureUtils.register("patch_wonderberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.WONDERBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_MULBERRY_BUSH = FeatureUtils.register("patch_mulberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.MULBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_LINGONBERRY_BUSH = FeatureUtils.register("patch_lingonberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.LINGONBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_CRANBERRY_BUSH = FeatureUtils.register("patch_cranberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.CRANBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_DEWBERRY_BUSH = FeatureUtils.register("patch_dewberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.DEWBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_THIMBLEBERRY_BUSH = FeatureUtils.register("patch_thimbleberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.THIMBLEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_GOOSEBERRY_BUSH = FeatureUtils.register("patch_gooseberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.GOOSEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_CHOKEBERRY_BUSH = FeatureUtils.register("patch_chokeberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.CHOKEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_OLALLIEBERRY_BUSH = FeatureUtils.register("patch_olallieberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.OLALLIEBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_ACEROLA_CHERRY_BUSH = FeatureUtils.register("patch_acerola_cherry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.ACEROLA_CHERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BARBERRY_BUSH = FeatureUtils.register("patch_barberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BARBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_BAYBERRY_BUSH = FeatureUtils.register("patch_bayberry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.BAYBERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));
    public static final ConfiguredFeature<?, ?> PATCH_GOGI_BERRY_BUSH = FeatureUtils.register("patch_gogi_berry_bush", Feature.RANDOM_PATCH.configured(FeatureUtils.simplePatchConfiguration(Feature.SIMPLE_BLOCK.configured(new SimpleBlockConfiguration(BlockStateProvider.simple(BlockInit.GOGI_BERRY_BUSH.get().defaultBlockState().setValue(SweetBerryBushBlock.AGE, Integer.valueOf(3))))), List.of(Blocks.GRASS_BLOCK))));

}
