package io.github.cjcj55.chrispymod.core.world.feature;

import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.world.level.levelgen.placement.BiomeFilter;
import net.minecraft.world.level.levelgen.placement.InSquarePlacement;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.minecraft.world.level.levelgen.placement.RarityFilter;

public class CMVegetationPlacements {
    public static final PlacedFeature PATCH_STRAWBERRY_COMMON = PlacementUtils.register("patch_strawberry_common", CMVegetationFeatures.PATCH_STRAWBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BLUEBERRY_COMMON = PlacementUtils.register("patch_blueberry_common", CMVegetationFeatures.PATCH_BLUEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_LOGANBERRY_COMMON = PlacementUtils.register("patch_loganberry_common", CMVegetationFeatures.PATCH_LOGANBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_RED_RASPBERRY_COMMON = PlacementUtils.register("patch_red_raspberry_common", CMVegetationFeatures.PATCH_RED_RASPBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BLACK_RASPBERRY_COMMON = PlacementUtils.register("patch_black_raspberry_common", CMVegetationFeatures.PATCH_BLACK_RASPBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_GOLDEN_RASPBERRY_COMMON = PlacementUtils.register("patch_golden_raspberry_common", CMVegetationFeatures.PATCH_GOLDEN_RASPBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_WHITE_RASPBERRY_COMMON = PlacementUtils.register("patch_white_raspberry_common", CMVegetationFeatures.PATCH_WHITE_RASPBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_MARIONBERRY_COMMON = PlacementUtils.register("patch_marionberry_common", CMVegetationFeatures.PATCH_MARIONBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BLACKCURRANT_COMMON = PlacementUtils.register("patch_blackcurrant_common", CMVegetationFeatures.PATCH_BLACKCURRANT_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_REDCURRANT_COMMON = PlacementUtils.register("patch_redcurrant_common", CMVegetationFeatures.PATCH_REDCURRANT_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_HUCKLEBERRY_COMMON = PlacementUtils.register("patch_huckleberry_common", CMVegetationFeatures.PATCH_HUCKLEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_WINEBERRY_COMMON = PlacementUtils.register("patch_wineberry_common", CMVegetationFeatures.PATCH_WINEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_ELDERBERRY_COMMON = PlacementUtils.register("patch_elderberry_common", CMVegetationFeatures.PATCH_ELDERBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BLACKBERRY_COMMON = PlacementUtils.register("patch_blackberry_common", CMVegetationFeatures.PATCH_BLACKBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BOYSENBERRY_COMMON = PlacementUtils.register("patch_boysenberry_common", CMVegetationFeatures.PATCH_BOYSENBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_GROUND_CHERRY_COMMON = PlacementUtils.register("patch_ground_cherry_common", CMVegetationFeatures.PATCH_GROUND_CHERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_ARONIA_BERRY_COMMON = PlacementUtils.register("patch_aronia_berry_common", CMVegetationFeatures.PATCH_ARONIA_BERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_SERVICEBERRY_COMMON = PlacementUtils.register("patch_serviceberry_common", CMVegetationFeatures.PATCH_SERVICEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_WONDERBERRY_COMMON = PlacementUtils.register("patch_wonderberry_common", CMVegetationFeatures.PATCH_WONDERBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_MULBERRY_COMMON = PlacementUtils.register("patch_mulberry_common", CMVegetationFeatures.PATCH_MULBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_LINGONBERRY_COMMON = PlacementUtils.register("patch_lingonberry_common", CMVegetationFeatures.PATCH_LINGONBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_CRANBERRY_COMMON = PlacementUtils.register("patch_cranberry_common", CMVegetationFeatures.PATCH_CRANBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_DEWBERRY_COMMON = PlacementUtils.register("patch_dewberry_common", CMVegetationFeatures.PATCH_DEWBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_THIMBLEBERRY_COMMON = PlacementUtils.register("patch_thimbleberry_common", CMVegetationFeatures.PATCH_THIMBLEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_GOOSEBERRY_COMMON = PlacementUtils.register("patch_gooseberry_common", CMVegetationFeatures.PATCH_GOOSEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_CHOKEBERRY_COMMON = PlacementUtils.register("patch_chokeberry_common", CMVegetationFeatures.PATCH_CHOKEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_OLALLIEBERRY_COMMON = PlacementUtils.register("patch_olallieberry_common", CMVegetationFeatures.PATCH_OLALLIEBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_ACEROLA_CHERRY_COMMON = PlacementUtils.register("patch_acerola_cherry_common", CMVegetationFeatures.PATCH_ACEROLA_CHERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BARBERRY_COMMON = PlacementUtils.register("patch_barberry_common", CMVegetationFeatures.PATCH_BARBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_BAYBERRY_COMMON = PlacementUtils.register("patch_bayberry_common", CMVegetationFeatures.PATCH_BAYBERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
    public static final PlacedFeature PATCH_GOGI_BERRY_COMMON = PlacementUtils.register("patch_gogi_berry_common", CMVegetationFeatures.PATCH_GOGI_BERRY_BUSH.placed(RarityFilter.onAverageOnceEvery(128), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_WORLD_SURFACE, BiomeFilter.biome()));
}
