package io.github.cjcj55.chrispymod.common.tags;

import io.github.cjcj55.chrispymod.ChrispyMod;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.common.Tags;

public class ModItemTags {
    public static final TagKey<Item> RUBY_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "ruby_ore"));
    public static final TagKey<Item> OPAL_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "opal_ore"));
    public static final TagKey<Item> TANGERINE_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "tangerine_ore"));
    public static final TagKey<Item> COBALT_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "cobalt_ore"));
    public static final TagKey<Item> PARYTH_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "paryth_ore"));
    public static final TagKey<Item> WHITE_DWARF_STAR_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "white_dwarf_star_ore"));
    public static final TagKey<Item> NATURAL_ESSENCE_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "natural_essence_ore"));
    public static final TagKey<Item> EXPERIENCE_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "experience_ore"));
    public static final TagKey<Item> ALUMINUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "aluminum_ore"));
    public static final TagKey<Item> ANTIMONY_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "antimony_ore"));
    public static final TagKey<Item> ARSENIC_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "arsenic_ore"));
    public static final TagKey<Item> BARIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "barium_ore"));
    public static final TagKey<Item> BERYLLIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "beryllium_ore"));
    public static final TagKey<Item> BISMUTH_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "bismuth_ore"));
    public static final TagKey<Item> BORON_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "boron_ore"));
    public static final TagKey<Item> CADMIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "cadmium_ore"));
    public static final TagKey<Item> CALCIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "calcium_ore"));
    public static final TagKey<Item> CERIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "cerium_ore"));
    public static final TagKey<Item> CESIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "cesium_ore"));
    public static final TagKey<Item> CHROMIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "chromium_ore"));
    public static final TagKey<Item> DYSPROSIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "dysprosium_ore"));
    public static final TagKey<Item> ERBIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "erbium_ore"));
    public static final TagKey<Item> EUROPIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "europium_ore"));
    public static final TagKey<Item> FRANCIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "francium_ore"));
    public static final TagKey<Item> GADOLINIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "gadolinium_ore"));
    public static final TagKey<Item> GALLIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "gallium_ore"));
    public static final TagKey<Item> GERMANIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "germanium_ore"));
    public static final TagKey<Item> HAFNIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "hafnium_ore"));
    public static final TagKey<Item> HOLMIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "holmium_ore"));
    public static final TagKey<Item> INDIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "indium_ore"));
    public static final TagKey<Item> IRIDIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "iridium_ore"));
    public static final TagKey<Item> LANTHANUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "lanthanum_ore"));
    public static final TagKey<Item> LEAD_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "lead_ore"));
    public static final TagKey<Item> LITHIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "lithium_ore"));
    public static final TagKey<Item> LUTETIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "lutetium_ore"));
    public static final TagKey<Item> MAGNESIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "magnesium_ore"));
    public static final TagKey<Item> MANGANESE_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "manganese_ore"));
    public static final TagKey<Item> MERCURY_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "mercury_ore"));
    public static final TagKey<Item> MYTHRIL_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "mythril_ore"));
    public static final TagKey<Item> MOLYBDENUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "molybdenum_ore"));
    public static final TagKey<Item> NEODYMIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "neodymium_ore"));
    public static final TagKey<Item> NICKEL_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "nickel_ore"));
    public static final TagKey<Item> OSMIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "osmium_ore"));
    public static final TagKey<Item> PALLADIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "palladium_ore"));
    public static final TagKey<Item> PLATINUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "platinum_ore"));
    public static final TagKey<Item> PLUTONIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "plutonium_ore"));
    public static final TagKey<Item> POLONIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "polonium_ore"));
    public static final TagKey<Item> POTASSIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "potassium_ore"));
    public static final TagKey<Item> PRASEODYMIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "praseodymium_ore"));
    public static final TagKey<Item> PROMETHIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "promethium_ore"));
    public static final TagKey<Item> RADIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "radium_ore"));
    public static final TagKey<Item> RHODIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "rhodium_ore"));
    public static final TagKey<Item> RUTHENIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "ruthenium_ore"));
    public static final TagKey<Item> SAMARIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "samarium_ore"));
    public static final TagKey<Item> SCANDIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "scandium_ore"));
    public static final TagKey<Item> SELENIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "selenium_ore"));
    public static final TagKey<Item> SILICON_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "silicon_ore"));
    public static final TagKey<Item> SILVER_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "silver_ore"));
    public static final TagKey<Item> SODIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "sodium_ore"));
    public static final TagKey<Item> STRONTIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "strontium_ore"));
    public static final TagKey<Item> TELLURIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "tellurium_ore"));
    public static final TagKey<Item> TERBIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "terbium_ore"));
    public static final TagKey<Item> THALLIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "thallium_ore"));
    public static final TagKey<Item> THORIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "thorium_ore"));
    public static final TagKey<Item> THULIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "thulium_ore"));
    public static final TagKey<Item> TIN_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "tin_ore"));
    public static final TagKey<Item> TITANIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "titanium_ore"));
    public static final TagKey<Item> URANIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "uranium_ore"));
    public static final TagKey<Item> VANADIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "vanadium_ore"));
    public static final TagKey<Item> VIBRANIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "vibranium_ore"));
    public static final TagKey<Item> YTTERBIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "ytterbium_ore"));
    public static final TagKey<Item> YTTRIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "yttrium_ore"));
    public static final TagKey<Item> ZIRCONIUM_ORE = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "zirconium_ore"));
    
    
    public static final TagKey<Item> BERRIES = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "berries"));
    public static final TagKey<Item> BERRY_JAMS = ItemTags.create(new ResourceLocation(ChrispyMod.MODID, "berry_jams"));

    //public static final Tags.IOptionalNamedTag<Item> MYSTERIOUS_ORE_ITEM = ItemTags.createOptional(new ResourceLocation(TutorialV3.MODID, "mysterious_ore"));
}
