package io.github.cjcj55.chrispymod.datagen;

import io.github.cjcj55.chrispymod.ChrispyMod;
import io.github.cjcj55.chrispymod.common.item.ChrispyModItem;
import io.github.cjcj55.chrispymod.core.init.BlockInit;
import io.github.cjcj55.chrispymod.core.init.ItemInit;
import net.minecraft.data.DataGenerator;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.client.model.generators.ItemModelBuilder;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.RegistryObject;

public class CMItemModelProvider extends ItemModelProvider {

    public CMItemModelProvider(DataGenerator generator, ExistingFileHelper existingFileHelper) {
        super(generator, ChrispyMod.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        simpleItem(ItemInit.STRAWBERRY);
        simpleItem(ItemInit.BLUEBERRY);
        simpleItem(ItemInit.LOGANBERRY);
        simpleItem(ItemInit.RED_RASPBERRY);
        simpleItem(ItemInit.BLACK_RASPBERRY);
        simpleItem(ItemInit.GOLDEN_RASPBERRY);
        simpleItem(ItemInit.WHITE_RASPBERRY);
        simpleItem(ItemInit.MARIONBERRY);
        simpleItem(ItemInit.BLACKCURRANT);
        simpleItem(ItemInit.REDCURRANT);
        simpleItem(ItemInit.HUCKLEBERRY);
        simpleItem(ItemInit.WINEBERRY);
        simpleItem(ItemInit.ELDERBERRY);
        simpleItem(ItemInit.BLACKBERRY);
        simpleItem(ItemInit.BOYSENBERRY);
        simpleItem(ItemInit.GROUND_CHERRY);
        simpleItem(ItemInit.ARONIA_BERRY);
        simpleItem(ItemInit.SERVICEBERRY);
        simpleItem(ItemInit.WONDERBERRY);
        simpleItem(ItemInit.MULBERRY);
        simpleItem(ItemInit.LINGONBERRY);
        simpleItem(ItemInit.CRANBERRY);
        simpleItem(ItemInit.DEWBERRY);
        simpleItem(ItemInit.THIMBLEBERRY);
        simpleItem(ItemInit.GOOSEBERRY);
        simpleItem(ItemInit.CHOKEBERRY);
        simpleItem(ItemInit.OLALLIEBERRY);
        simpleItem(ItemInit.ACEROLA_CHERRY);
        simpleItem(ItemInit.BARBERRY);
        simpleItem(ItemInit.BAYBERRY);
        simpleItem(ItemInit.GOGI_BERRY);

        simpleItem(ItemInit.MASON_JAR);

        simpleItem(ItemInit.STRAWBERRY_JAM);
        simpleItem(ItemInit.BLUEBERRY_JAM);
        simpleItem(ItemInit.LOGANBERRY_JAM);
        simpleItem(ItemInit.RED_RASPBERRY_JAM);
        simpleItem(ItemInit.BLACK_RASPBERRY_JAM);
        simpleItem(ItemInit.GOLDEN_RASPBERRY_JAM);
        simpleItem(ItemInit.WHITE_RASPBERRY_JAM);
        simpleItem(ItemInit.MARIONBERRY_JAM);
        simpleItem(ItemInit.BLACKCURRANT_JAM);
        simpleItem(ItemInit.REDCURRANT_JAM);
        simpleItem(ItemInit.HUCKLEBERRY_JAM);
        simpleItem(ItemInit.WINEBERRY_JAM);
        simpleItem(ItemInit.ELDERBERRY_JAM);
        simpleItem(ItemInit.BLACKBERRY_JAM);
        simpleItem(ItemInit.BOYSENBERRY_JAM);
        simpleItem(ItemInit.GROUND_CHERRY_JAM);
        simpleItem(ItemInit.ARONIA_BERRY_JAM);
        simpleItem(ItemInit.SERVICEBERRY_JAM);
        simpleItem(ItemInit.WONDERBERRY_JAM);
        simpleItem(ItemInit.MULBERRY_JAM);
        simpleItem(ItemInit.LINGONBERRY_JAM);
        simpleItem(ItemInit.CRANBERRY_JAM);
        simpleItem(ItemInit.DEWBERRY_JAM);
        simpleItem(ItemInit.THIMBLEBERRY_JAM);
        simpleItem(ItemInit.GOOSEBERRY_JAM);
        simpleItem(ItemInit.CHOKEBERRY_JAM);
        simpleItem(ItemInit.OLALLIEBERRY_JAM);
        simpleItem(ItemInit.ACEROLA_CHERRY_JAM);
        simpleItem(ItemInit.BARBERRY_JAM);
        simpleItem(ItemInit.BAYBERRY_JAM);
        simpleItem(ItemInit.GOGI_BERRY_JAM);

        blockItem(BlockInit.ALUMINUM_ORE);
        blockItem(BlockInit.DEEPSLATE_ALUMINUM_ORE);
        blockItem(BlockInit.ANTIMONY_ORE);
        blockItem(BlockInit.DEEPSLATE_ANTIMONY_ORE);
        blockItem(BlockInit.ARSENIC_ORE);
        blockItem(BlockInit.DEEPSLATE_ARSENIC_ORE);
        blockItem(BlockInit.BARIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_BARIUM_ORE);
        blockItem(BlockInit.BERYLLIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_BERYLLIUM_ORE);
        blockItem(BlockInit.BISMUTH_ORE);
        blockItem(BlockInit.DEEPSLATE_BISMUTH_ORE);
        blockItem(BlockInit.BORON_ORE);
        blockItem(BlockInit.DEEPSLATE_BORON_ORE);
        blockItem(BlockInit.CADMIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_CADMIUM_ORE);
        blockItem(BlockInit.CALCIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_CALCIUM_ORE);
        blockItem(BlockInit.CERIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_CERIUM_ORE);
        blockItem(BlockInit.CESIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_CESIUM_ORE);
        blockItem(BlockInit.CHROMIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_CHROMIUM_ORE);
        blockItem(BlockInit.DYSPROSIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_DYSPROSIUM_ORE);
        blockItem(BlockInit.ERBIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_ERBIUM_ORE);
        blockItem(BlockInit.EUROPIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_EUROPIUM_ORE);
        blockItem(BlockInit.FRANCIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_FRANCIUM_ORE);
        blockItem(BlockInit.GADOLINIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_GADOLINIUM_ORE);
        blockItem(BlockInit.GALLIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_GALLIUM_ORE);
        blockItem(BlockInit.GERMANIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_GERMANIUM_ORE);
        blockItem(BlockInit.HAFNIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_HAFNIUM_ORE);
        blockItem(BlockInit.HOLMIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_HOLMIUM_ORE);
        blockItem(BlockInit.INDIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_INDIUM_ORE);
        blockItem(BlockInit.IRIDIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_IRIDIUM_ORE);
        blockItem(BlockInit.LANTHANUM_ORE);
        blockItem(BlockInit.DEEPSLATE_LANTHANUM_ORE);
        blockItem(BlockInit.LEAD_ORE);
        blockItem(BlockInit.DEEPSLATE_LEAD_ORE);
        blockItem(BlockInit.LITHIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_LITHIUM_ORE);
        blockItem(BlockInit.LUTETIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_LUTETIUM_ORE);
        blockItem(BlockInit.MAGNESIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_MAGNESIUM_ORE);
        blockItem(BlockInit.MANGANESE_ORE);
        blockItem(BlockInit.DEEPSLATE_MANGANESE_ORE);
        blockItem(BlockInit.MERCURY_ORE);
        blockItem(BlockInit.DEEPSLATE_MERCURY_ORE);
        blockItem(BlockInit.MYTHRIL_ORE);
        blockItem(BlockInit.DEEPSLATE_MYTHRIL_ORE);
        blockItem(BlockInit.MOLYBDENUM_ORE);
        blockItem(BlockInit.DEEPSLATE_MOLYBDENUM_ORE);
        blockItem(BlockInit.NEODYMIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_NEODYMIUM_ORE);
        blockItem(BlockInit.NICKEL_ORE);
        blockItem(BlockInit.DEEPSLATE_NICKEL_ORE);
        blockItem(BlockInit.OSMIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_OSMIUM_ORE);
        blockItem(BlockInit.PALLADIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_PALLADIUM_ORE);
        blockItem(BlockInit.PLATINUM_ORE);
        blockItem(BlockInit.DEEPSLATE_PLATINUM_ORE);
        blockItem(BlockInit.PLUTONIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_PLUTONIUM_ORE);
        blockItem(BlockInit.POLONIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_POLONIUM_ORE);
        blockItem(BlockInit.POTASSIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_POTASSIUM_ORE);
        blockItem(BlockInit.PRASEODYMIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_PRASEODYMIUM_ORE);
        blockItem(BlockInit.PROMETHIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_PROMETHIUM_ORE);
        blockItem(BlockInit.RADIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_RADIUM_ORE);
        blockItem(BlockInit.RHODIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_RHODIUM_ORE);
        blockItem(BlockInit.RUTHENIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_RUTHENIUM_ORE);
        blockItem(BlockInit.SAMARIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_SAMARIUM_ORE);
        blockItem(BlockInit.SCANDIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_SCANDIUM_ORE);
        blockItem(BlockInit.SELENIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_SELENIUM_ORE);
        blockItem(BlockInit.SILICON_ORE);
        blockItem(BlockInit.DEEPSLATE_SILICON_ORE);
        blockItem(BlockInit.SILVER_ORE);
        blockItem(BlockInit.DEEPSLATE_SILVER_ORE);
        blockItem(BlockInit.SODIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_SODIUM_ORE);
        blockItem(BlockInit.STRONTIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_STRONTIUM_ORE);
        blockItem(BlockInit.TELLURIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_TELLURIUM_ORE);
        blockItem(BlockInit.TERBIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_TERBIUM_ORE);
        blockItem(BlockInit.THALLIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_THALLIUM_ORE);
        blockItem(BlockInit.THORIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_THORIUM_ORE);
        blockItem(BlockInit.THULIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_THULIUM_ORE);
        blockItem(BlockInit.TIN_ORE);
        blockItem(BlockInit.DEEPSLATE_TIN_ORE);
        blockItem(BlockInit.TITANIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_TITANIUM_ORE);
        blockItem(BlockInit.URANIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_URANIUM_ORE);
        blockItem(BlockInit.VANADIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_VANADIUM_ORE);
        blockItem(BlockInit.VIBRANIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_VIBRANIUM_ORE);
        blockItem(BlockInit.YTTERBIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_YTTERBIUM_ORE);
        blockItem(BlockInit.YTTRIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_YTTRIUM_ORE);
        blockItem(BlockInit.ZIRCONIUM_ORE);
        blockItem(BlockInit.DEEPSLATE_ZIRCONIUM_ORE);

        simpleItem(ItemInit.ALUMINUM);
        simpleItem(ItemInit.RAW_ALUMINUM);
        simpleItem(ItemInit.ANTIMONY);
        simpleItem(ItemInit.RAW_ANTIMONY);
        simpleItem(ItemInit.ARSENIC);
        simpleItem(ItemInit.RAW_ARSENIC);
        simpleItem(ItemInit.BARIUM);
        simpleItem(ItemInit.RAW_BARIUM);
        simpleItem(ItemInit.BERYLLIUM);
        simpleItem(ItemInit.RAW_BERYLLIUM);
        simpleItem(ItemInit.BISMUTH);
        simpleItem(ItemInit.RAW_BISMUTH);
        simpleItem(ItemInit.BORON);
        simpleItem(ItemInit.RAW_BORON);
        simpleItem(ItemInit.CADMIUM);
        simpleItem(ItemInit.RAW_CADMIUM);
        simpleItem(ItemInit.CALCIUM);
        simpleItem(ItemInit.RAW_CALCIUM);
        simpleItem(ItemInit.CERIUM);
        simpleItem(ItemInit.RAW_CERIUM);
        simpleItem(ItemInit.CESIUM);
        simpleItem(ItemInit.RAW_CESIUM);
        simpleItem(ItemInit.CHROMIUM);
        simpleItem(ItemInit.RAW_CHROMIUM);
        simpleItem(ItemInit.DYSPROSIUM);
        simpleItem(ItemInit.RAW_DYSPROSIUM);
        simpleItem(ItemInit.ERBIUM);
        simpleItem(ItemInit.RAW_ERBIUM);
        simpleItem(ItemInit.EUROPIUM);
        simpleItem(ItemInit.RAW_EUROPIUM);
        simpleItem(ItemInit.FRANCIUM);
        simpleItem(ItemInit.RAW_FRANCIUM);
        simpleItem(ItemInit.GADOLINIUM);
        simpleItem(ItemInit.RAW_GADOLINIUM);
        simpleItem(ItemInit.GALLIUM);
        simpleItem(ItemInit.RAW_GALLIUM);
        simpleItem(ItemInit.GERMANIUM);
        simpleItem(ItemInit.RAW_GERMANIUM);
        simpleItem(ItemInit.HAFNIUM);
        simpleItem(ItemInit.RAW_HAFNIUM);
        simpleItem(ItemInit.HOLMIUM);
        simpleItem(ItemInit.RAW_HOLMIUM);
        simpleItem(ItemInit.INDIUM);
        simpleItem(ItemInit.RAW_INDIUM);
        simpleItem(ItemInit.IRIDIUM);
        simpleItem(ItemInit.RAW_IRIDIUM);
        simpleItem(ItemInit.LANTHANUM);
        simpleItem(ItemInit.RAW_LANTHANUM);
        simpleItem(ItemInit.LEAD);
        simpleItem(ItemInit.RAW_LEAD);
        simpleItem(ItemInit.LITHIUM);
        simpleItem(ItemInit.RAW_LITHIUM);
        simpleItem(ItemInit.LUTETIUM);
        simpleItem(ItemInit.RAW_LUTETIUM);
        simpleItem(ItemInit.MAGNESIUM);
        simpleItem(ItemInit.RAW_MAGNESIUM);
        simpleItem(ItemInit.MANGANESE);
        simpleItem(ItemInit.RAW_MANGANESE);
        simpleItem(ItemInit.MERCURY);
        simpleItem(ItemInit.RAW_MERCURY);
        simpleItem(ItemInit.MYTHRIL);
        simpleItem(ItemInit.RAW_MYTHRIL);
        simpleItem(ItemInit.MOLYBDENUM);
        simpleItem(ItemInit.RAW_MOLYBDENUM);
        simpleItem(ItemInit.NEODYMIUM);
        simpleItem(ItemInit.RAW_NEODYMIUM);
        simpleItem(ItemInit.NICKEL);
        simpleItem(ItemInit.RAW_NICKEL);
        simpleItem(ItemInit.OSMIUM);
        simpleItem(ItemInit.RAW_OSMIUM);
        simpleItem(ItemInit.PALLADIUM);
        simpleItem(ItemInit.RAW_PALLADIUM);
        simpleItem(ItemInit.PLATINUM);
        simpleItem(ItemInit.RAW_PLATINUM);
        simpleItem(ItemInit.PLUTONIUM);
        simpleItem(ItemInit.RAW_PLUTONIUM);
        simpleItem(ItemInit.POLONIUM);
        simpleItem(ItemInit.RAW_POLONIUM);
        simpleItem(ItemInit.POTASSIUM);
        simpleItem(ItemInit.RAW_POTASSIUM);
        simpleItem(ItemInit.PRASEODYMIUM);
        simpleItem(ItemInit.RAW_PRASEODYMIUM);
        simpleItem(ItemInit.PROMETHIUM);
        simpleItem(ItemInit.RAW_PROMETHIUM);
        simpleItem(ItemInit.RADIUM);
        simpleItem(ItemInit.RAW_RADIUM);
        simpleItem(ItemInit.RHODIUM);
        simpleItem(ItemInit.RAW_RHODIUM);
        simpleItem(ItemInit.RUTHENIUM);
        simpleItem(ItemInit.RAW_RUTHENIUM);
        simpleItem(ItemInit.SAMARIUM);
        simpleItem(ItemInit.RAW_SAMARIUM);
        simpleItem(ItemInit.SCANDIUM);
        simpleItem(ItemInit.RAW_SCANDIUM);
        simpleItem(ItemInit.SELENIUM);
        simpleItem(ItemInit.RAW_SELENIUM);
        simpleItem(ItemInit.SILICON);
        simpleItem(ItemInit.RAW_SILICON);
        simpleItem(ItemInit.SILVER);
        simpleItem(ItemInit.RAW_SILVER);
        simpleItem(ItemInit.SODIUM);
        simpleItem(ItemInit.RAW_SODIUM);
        simpleItem(ItemInit.STRONTIUM);
        simpleItem(ItemInit.RAW_STRONTIUM);
        simpleItem(ItemInit.TELLURIUM);
        simpleItem(ItemInit.RAW_TELLURIUM);
        simpleItem(ItemInit.TERBIUM);
        simpleItem(ItemInit.RAW_TERBIUM);
        simpleItem(ItemInit.THALLIUM);
        simpleItem(ItemInit.RAW_THALLIUM);
        simpleItem(ItemInit.THORIUM);
        simpleItem(ItemInit.RAW_THORIUM);
        simpleItem(ItemInit.THULIUM);
        simpleItem(ItemInit.RAW_THULIUM);
        simpleItem(ItemInit.TIN);
        simpleItem(ItemInit.RAW_TIN);
        simpleItem(ItemInit.TITANIUM);
        simpleItem(ItemInit.RAW_TITANIUM);
        simpleItem(ItemInit.URANIUM);
        simpleItem(ItemInit.RAW_URANIUM);
        simpleItem(ItemInit.VANADIUM);
        simpleItem(ItemInit.RAW_VANADIUM);
        simpleItem(ItemInit.VIBRANIUM);
        simpleItem(ItemInit.RAW_VIBRANIUM);
        simpleItem(ItemInit.YTTERBIUM);
        simpleItem(ItemInit.RAW_YTTERBIUM);
        simpleItem(ItemInit.YTTRIUM);
        simpleItem(ItemInit.RAW_YTTRIUM);
        simpleItem(ItemInit.ZIRCONIUM);
        simpleItem(ItemInit.RAW_ZIRCONIUM);
    }
    private ItemModelBuilder simpleItem(RegistryObject<Item> item) {
        return withExistingParent(item.getId().getPath(),
                new ResourceLocation("item/generated")).texture("layer0",
                new ResourceLocation(ChrispyMod.MODID, "item/" + item.getId().getPath()));
    }

    private ItemModelBuilder handheldItem(RegistryObject<Item> item) {
        return withExistingParent(item.getId().getPath(),
                new ResourceLocation("item/handheld")).texture("layer0",
                new ResourceLocation(ChrispyMod.MODID,"item/" + item.getId().getPath()));
    }

    private ItemModelBuilder blockItem(RegistryObject<Block> block) {
        return withExistingParent(block.getId().getPath(),
                new ResourceLocation(ChrispyMod.MODID, "block/" + block.getId().getPath()));
    }
}
