package github.cjcj55.chrispymod.datagen;

import github.cjcj55.chrispymod.ChrispyMod;
import github.cjcj55.chrispymod.registry.CMBlocks;
import github.cjcj55.chrispymod.util.CMBlockTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.minecraftforge.common.Tags;
import net.minecraftforge.common.data.BlockTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class CMBlockTagGenerator extends BlockTagsProvider {
    public CMBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, ChrispyMod.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider pProvider) {
        //this.tag(BlockTags.CROPS)
        this.tag(Tags.Blocks.ORES)
                .add(CMBlocks.RUBY_ORE.get())
                .add(CMBlocks.DEEPSLATE_RUBY_ORE.get())
                .add(CMBlocks.RUBY_ORE_NETHER.get())
                .add(CMBlocks.OPAL_ORE.get())
                .add(CMBlocks.DEEPSLATE_OPAL_ORE.get())
                .add(CMBlocks.TANGERINE_ORE.get())
                .add(CMBlocks.DEEPSLATE_TANGERINE_ORE.get())
                .add(CMBlocks.COBALT_ORE.get())
                .add(CMBlocks.DEEPSLATE_COBALT_ORE.get())
                .add(CMBlocks.PARYTH_ORE.get())
                .add(CMBlocks.DEEPSLATE_PARYTH_ORE.get())
                .add(CMBlocks.WHITE_DWARF_STAR_ORE.get())
                .add(CMBlocks.DEEPSLATE_WHITE_DWARF_STAR_ORE.get())
                .add(CMBlocks.NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.EXPERIENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_EXPERIENCE_ORE.get())
                .add(CMBlocks.FLAME_ORE_NETHER.get())
                .add(CMBlocks.HELLFIRE_ORE_NETHER.get());
//                .add(CMBlocks.ALUMINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ALUMINUM_ORE.get())
//                .add(CMBlocks.ANTIMONY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ANTIMONY_ORE.get())
//                .add(CMBlocks.ARSENIC_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ARSENIC_ORE.get())
//                .add(CMBlocks.BARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BARIUM_ORE.get())
//                .add(CMBlocks.BERYLLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BERYLLIUM_ORE.get())
//                .add(CMBlocks.BISMUTH_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BISMUTH_ORE.get())
//                .add(CMBlocks.BORON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BORON_ORE.get())
//                .add(CMBlocks.CADMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CADMIUM_ORE.get())
//                .add(CMBlocks.CALCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CALCIUM_ORE.get())
//                .add(CMBlocks.CERIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CERIUM_ORE.get())
//                .add(CMBlocks.CESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CESIUM_ORE.get())
//                .add(CMBlocks.CHROMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CHROMIUM_ORE.get())
//                .add(CMBlocks.DYSPROSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_DYSPROSIUM_ORE.get())
//                .add(CMBlocks.ERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ERBIUM_ORE.get())
//                .add(CMBlocks.EUROPIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_EUROPIUM_ORE.get())
//                .add(CMBlocks.FRANCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_FRANCIUM_ORE.get())
//                .add(CMBlocks.GADOLINIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GADOLINIUM_ORE.get())
//                .add(CMBlocks.GALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GALLIUM_ORE.get())
//                .add(CMBlocks.GERMANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GERMANIUM_ORE.get())
//                .add(CMBlocks.HAFNIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HAFNIUM_ORE.get())
//                .add(CMBlocks.HOLMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HOLMIUM_ORE.get())
//                .add(CMBlocks.INDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_INDIUM_ORE.get())
//                .add(CMBlocks.IRIDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_IRIDIUM_ORE.get())
//                .add(CMBlocks.LANTHANUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LANTHANUM_ORE.get())
//                .add(CMBlocks.LEAD_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LEAD_ORE.get())
//                .add(CMBlocks.LITHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LITHIUM_ORE.get())
//                .add(CMBlocks.LUTETIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LUTETIUM_ORE.get())
//                .add(CMBlocks.MAGNESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MAGNESIUM_ORE.get())
//                .add(CMBlocks.MANGANESE_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MANGANESE_ORE.get())
//                .add(CMBlocks.MERCURY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MERCURY_ORE.get())
//                .add(CMBlocks.MYTHRIL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MYTHRIL_ORE.get())
//                .add(CMBlocks.MOLYBDENUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MOLYBDENUM_ORE.get())
//                .add(CMBlocks.NEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NEODYMIUM_ORE.get())
//                .add(CMBlocks.NICKEL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NICKEL_ORE.get())
//                .add(CMBlocks.OSMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_OSMIUM_ORE.get())
//                .add(CMBlocks.PALLADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PALLADIUM_ORE.get())
//                .add(CMBlocks.PLATINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLATINUM_ORE.get())
//                .add(CMBlocks.PLUTONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLUTONIUM_ORE.get())
//                .add(CMBlocks.POLONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POLONIUM_ORE.get())
//                .add(CMBlocks.POTASSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POTASSIUM_ORE.get())
//                .add(CMBlocks.PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.PROMETHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PROMETHIUM_ORE.get())
//                .add(CMBlocks.RADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RADIUM_ORE.get())
//                .add(CMBlocks.RHODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RHODIUM_ORE.get())
//                .add(CMBlocks.RUTHENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RUTHENIUM_ORE.get())
//                .add(CMBlocks.SAMARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SAMARIUM_ORE.get())
//                .add(CMBlocks.SCANDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SCANDIUM_ORE.get())
//                .add(CMBlocks.SELENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SELENIUM_ORE.get())
//                .add(CMBlocks.SILICON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILICON_ORE.get())
//                .add(CMBlocks.SILVER_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILVER_ORE.get())
//                .add(CMBlocks.SODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SODIUM_ORE.get())
//                .add(CMBlocks.STRONTIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_STRONTIUM_ORE.get())
//                .add(CMBlocks.TELLURIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TELLURIUM_ORE.get())
//                .add(CMBlocks.TERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TERBIUM_ORE.get())
//                .add(CMBlocks.THALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THALLIUM_ORE.get())
//                .add(CMBlocks.THORIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THORIUM_ORE.get())
//                .add(CMBlocks.THULIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THULIUM_ORE.get())
//                .add(CMBlocks.TIN_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TIN_ORE.get())
//                .add(CMBlocks.TITANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TITANIUM_ORE.get())
//                .add(CMBlocks.URANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_URANIUM_ORE.get())
//                .add(CMBlocks.VANADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VANADIUM_ORE.get())
//                .add(CMBlocks.VIBRANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VIBRANIUM_ORE.get())
//                .add(CMBlocks.YTTERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTERBIUM_ORE.get())
//                .add(CMBlocks.YTTRIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTRIUM_ORE.get())
//                .add(CMBlocks.ZIRCONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ZIRCONIUM_ORE.get());

        this.tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(CMBlocks.BLUE_EMERALD_BLOCK.get())
                .add(CMBlocks.COBALT_BLOCK.get())
                .add(CMBlocks.COBALT_ORE.get())
                .add(CMBlocks.DEEPSLATE_COBALT_ORE.get())
                .add(CMBlocks.EXPERIENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_EXPERIENCE_ORE.get())
                .add(CMBlocks.FLAME_BLOCK.get())
                .add(CMBlocks.FLAME_ORE_NETHER.get())
                .add(CMBlocks.HARDENED_REDSTONE_BLOCK.get())
                .add(CMBlocks.HELLFIRE_ORE_NETHER.get())
                .add(CMBlocks.LIGHTNING_BLOCK.get())
                .add(CMBlocks.NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.OPAL_BLOCK.get())
                .add(CMBlocks.OPAL_ORE.get())
                .add(CMBlocks.DEEPSLATE_OPAL_ORE.get())
                .add(CMBlocks.PARYTH_BLOCK.get())
                .add(CMBlocks.PARYTH_ORE.get())
                .add(CMBlocks.DEEPSLATE_PARYTH_ORE.get())
                .add(CMBlocks.TANGERINE_BLOCK.get())
                .add(CMBlocks.TANGERINE_ORE.get())
                .add(CMBlocks.DEEPSLATE_TANGERINE_ORE.get())
                .add(CMBlocks.RUBY_BLOCK.get())
                .add(CMBlocks.RUBY_ORE.get())
                .add(CMBlocks.DEEPSLATE_RUBY_ORE.get())
                .add(CMBlocks.RUBY_ORE_NETHER.get())
                .add(CMBlocks.WHITE_DWARF_STAR_ORE.get())
                .add(CMBlocks.DEEPSLATE_WHITE_DWARF_STAR_ORE.get())
//                .add(CMBlocks.ALUMINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ALUMINUM_ORE.get())
//                .add(CMBlocks.ANTIMONY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ANTIMONY_ORE.get())
//                .add(CMBlocks.ARSENIC_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ARSENIC_ORE.get())
//                .add(CMBlocks.BARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BARIUM_ORE.get())
//                .add(CMBlocks.BERYLLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BERYLLIUM_ORE.get())
//                .add(CMBlocks.BISMUTH_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BISMUTH_ORE.get())
//                .add(CMBlocks.BORON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BORON_ORE.get())
//                .add(CMBlocks.CADMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CADMIUM_ORE.get())
//                .add(CMBlocks.CALCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CALCIUM_ORE.get())
//                .add(CMBlocks.CERIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CERIUM_ORE.get())
//                .add(CMBlocks.CESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CESIUM_ORE.get())
//                .add(CMBlocks.CHROMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CHROMIUM_ORE.get())
//                .add(CMBlocks.DYSPROSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_DYSPROSIUM_ORE.get())
//                .add(CMBlocks.ERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ERBIUM_ORE.get())
//                .add(CMBlocks.EUROPIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_EUROPIUM_ORE.get())
//                .add(CMBlocks.FRANCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_FRANCIUM_ORE.get())
//                .add(CMBlocks.GADOLINIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GADOLINIUM_ORE.get())
//                .add(CMBlocks.GALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GALLIUM_ORE.get())
//                .add(CMBlocks.GERMANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GERMANIUM_ORE.get())
//                .add(CMBlocks.HAFNIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HAFNIUM_ORE.get())
//                .add(CMBlocks.HOLMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HOLMIUM_ORE.get())
//                .add(CMBlocks.INDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_INDIUM_ORE.get())
//                .add(CMBlocks.IRIDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_IRIDIUM_ORE.get())
//                .add(CMBlocks.LANTHANUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LANTHANUM_ORE.get())
//                .add(CMBlocks.LEAD_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LEAD_ORE.get())
//                .add(CMBlocks.LITHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LITHIUM_ORE.get())
//                .add(CMBlocks.LUTETIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LUTETIUM_ORE.get())
//                .add(CMBlocks.MAGNESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MAGNESIUM_ORE.get())
//                .add(CMBlocks.MANGANESE_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MANGANESE_ORE.get())
//                .add(CMBlocks.MERCURY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MERCURY_ORE.get())
//                .add(CMBlocks.MYTHRIL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MYTHRIL_ORE.get())
//                .add(CMBlocks.MOLYBDENUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MOLYBDENUM_ORE.get())
//                .add(CMBlocks.NEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NEODYMIUM_ORE.get())
//                .add(CMBlocks.NICKEL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NICKEL_ORE.get())
//                .add(CMBlocks.OSMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_OSMIUM_ORE.get())
//                .add(CMBlocks.PALLADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PALLADIUM_ORE.get())
//                .add(CMBlocks.PLATINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLATINUM_ORE.get())
//                .add(CMBlocks.PLUTONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLUTONIUM_ORE.get())
//                .add(CMBlocks.POLONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POLONIUM_ORE.get())
//                .add(CMBlocks.POTASSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POTASSIUM_ORE.get())
//                .add(CMBlocks.PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.PROMETHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PROMETHIUM_ORE.get())
//                .add(CMBlocks.RADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RADIUM_ORE.get())
//                .add(CMBlocks.RHODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RHODIUM_ORE.get())
//                .add(CMBlocks.RUTHENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RUTHENIUM_ORE.get())
//                .add(CMBlocks.SAMARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SAMARIUM_ORE.get())
//                .add(CMBlocks.SCANDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SCANDIUM_ORE.get())
//                .add(CMBlocks.SELENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SELENIUM_ORE.get())
//                .add(CMBlocks.SILICON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILICON_ORE.get())
//                .add(CMBlocks.SILVER_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILVER_ORE.get())
//                .add(CMBlocks.SODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SODIUM_ORE.get())
//                .add(CMBlocks.STRONTIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_STRONTIUM_ORE.get())
//                .add(CMBlocks.TELLURIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TELLURIUM_ORE.get())
//                .add(CMBlocks.TERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TERBIUM_ORE.get())
//                .add(CMBlocks.THALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THALLIUM_ORE.get())
//                .add(CMBlocks.THORIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THORIUM_ORE.get())
//                .add(CMBlocks.THULIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THULIUM_ORE.get())
//                .add(CMBlocks.TIN_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TIN_ORE.get())
//                .add(CMBlocks.TITANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TITANIUM_ORE.get())
//                .add(CMBlocks.URANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_URANIUM_ORE.get())
//                .add(CMBlocks.VANADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VANADIUM_ORE.get())
//                .add(CMBlocks.VIBRANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VIBRANIUM_ORE.get())
//                .add(CMBlocks.YTTERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTERBIUM_ORE.get())
//                .add(CMBlocks.YTTRIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTRIUM_ORE.get())
//                .add(CMBlocks.ZIRCONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ZIRCONIUM_ORE.get())
                .add(CMBlocks.SKINNY_SLANTED_BRICKS.get())
                .add(CMBlocks.SLANTED_BRICKS.get())
                .add(CMBlocks.SKINNY_BRICKS.get())
                .add(CMBlocks.CIRCULAR_BRICKS.get())
                .add(CMBlocks.CRACKED_BRICKS.get())
                .add(CMBlocks.ENCASED_BRICKS.get())
                .add(CMBlocks.MOSAIC_BRICKS.get())
                .add(CMBlocks.ORNATE_BRICKS.get())
                .add(CMBlocks.ROAD_BRICKS.get())
                .add(CMBlocks.SOLID_BRICKS.get())
                .add(CMBlocks.WEAVER_BRICKS.get())
                .add(CMBlocks.ALLOY_FURNACE.get());
//                .add(CMBlocks.JAM_AND_JELLY_MAKER.get());

        this.tag(BlockTags.MINEABLE_WITH_AXE);

        this.tag(BlockTags.NEEDS_STONE_TOOL)
                .add(CMBlocks.EXPERIENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_EXPERIENCE_ORE.get())
                .add(CMBlocks.OPAL_BLOCK.get())
                .add(CMBlocks.OPAL_ORE.get())
                .add(CMBlocks.DEEPSLATE_OPAL_ORE.get())
                .add(CMBlocks.SKINNY_SLANTED_BRICKS.get())
                .add(CMBlocks.SLANTED_BRICKS.get())
                .add(CMBlocks.SKINNY_BRICKS.get())
                .add(CMBlocks.CIRCULAR_BRICKS.get())
                .add(CMBlocks.CRACKED_BRICKS.get())
                .add(CMBlocks.ENCASED_BRICKS.get())
                .add(CMBlocks.MOSAIC_BRICKS.get())
                .add(CMBlocks.ORNATE_BRICKS.get())
                .add(CMBlocks.ROAD_BRICKS.get())
                .add(CMBlocks.SOLID_BRICKS.get())
                .add(CMBlocks.WEAVER_BRICKS.get());

        this.tag(BlockTags.NEEDS_IRON_TOOL)
                .add(CMBlocks.FLAME_BLOCK.get())
                .add(CMBlocks.FLAME_ORE_NETHER.get())
                .add(CMBlocks.HARDENED_REDSTONE_BLOCK.get())
                .add(CMBlocks.HELLFIRE_ORE_NETHER.get())
                .add(CMBlocks.NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.PARYTH_BLOCK.get())
                .add(CMBlocks.PARYTH_ORE.get())
                .add(CMBlocks.DEEPSLATE_PARYTH_ORE.get())
                .add(CMBlocks.RUBY_BLOCK.get())
                .add(CMBlocks.RUBY_ORE.get())
                .add(CMBlocks.DEEPSLATE_RUBY_ORE.get())
                .add(CMBlocks.RUBY_ORE_NETHER.get())
                .add(CMBlocks.TANGERINE_BLOCK.get())
                .add(CMBlocks.TANGERINE_ORE.get())
                .add(CMBlocks.DEEPSLATE_TANGERINE_ORE.get());
//                .add(CMBlocks.ALUMINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ALUMINUM_ORE.get())
//                .add(CMBlocks.ANTIMONY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ANTIMONY_ORE.get())
//                .add(CMBlocks.ARSENIC_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ARSENIC_ORE.get())
//                .add(CMBlocks.BARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BARIUM_ORE.get())
//                .add(CMBlocks.BERYLLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BERYLLIUM_ORE.get())
//                .add(CMBlocks.BISMUTH_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BISMUTH_ORE.get())
//                .add(CMBlocks.BORON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BORON_ORE.get())
//                .add(CMBlocks.CADMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CADMIUM_ORE.get())
//                .add(CMBlocks.CALCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CALCIUM_ORE.get())
//                .add(CMBlocks.CERIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CERIUM_ORE.get())
//                .add(CMBlocks.CESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CESIUM_ORE.get())
//                .add(CMBlocks.CHROMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CHROMIUM_ORE.get())
//                .add(CMBlocks.DYSPROSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_DYSPROSIUM_ORE.get())
//                .add(CMBlocks.ERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ERBIUM_ORE.get())
//                .add(CMBlocks.EUROPIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_EUROPIUM_ORE.get())
//                .add(CMBlocks.FRANCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_FRANCIUM_ORE.get())
//                .add(CMBlocks.GADOLINIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GADOLINIUM_ORE.get())
//                .add(CMBlocks.GALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GALLIUM_ORE.get())
//                .add(CMBlocks.GERMANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GERMANIUM_ORE.get())
//                .add(CMBlocks.HAFNIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HAFNIUM_ORE.get())
//                .add(CMBlocks.HOLMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HOLMIUM_ORE.get())
//                .add(CMBlocks.INDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_INDIUM_ORE.get())
//                .add(CMBlocks.IRIDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_IRIDIUM_ORE.get())
//                .add(CMBlocks.LANTHANUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LANTHANUM_ORE.get())
//                .add(CMBlocks.LEAD_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LEAD_ORE.get())
//                .add(CMBlocks.LITHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LITHIUM_ORE.get())
//                .add(CMBlocks.LUTETIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LUTETIUM_ORE.get())
//                .add(CMBlocks.MAGNESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MAGNESIUM_ORE.get())
//                .add(CMBlocks.MANGANESE_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MANGANESE_ORE.get())
//                .add(CMBlocks.MERCURY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MERCURY_ORE.get())
//                .add(CMBlocks.MYTHRIL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MYTHRIL_ORE.get())
//                .add(CMBlocks.MOLYBDENUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MOLYBDENUM_ORE.get())
//                .add(CMBlocks.NEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NEODYMIUM_ORE.get())
//                .add(CMBlocks.NICKEL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NICKEL_ORE.get())
//                .add(CMBlocks.OSMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_OSMIUM_ORE.get())
//                .add(CMBlocks.PALLADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PALLADIUM_ORE.get())
//                .add(CMBlocks.PLATINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLATINUM_ORE.get())
//                .add(CMBlocks.PLUTONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLUTONIUM_ORE.get())
//                .add(CMBlocks.POLONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POLONIUM_ORE.get())
//                .add(CMBlocks.POTASSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POTASSIUM_ORE.get())
//                .add(CMBlocks.PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.PROMETHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PROMETHIUM_ORE.get())
//                .add(CMBlocks.RADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RADIUM_ORE.get())
//                .add(CMBlocks.RHODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RHODIUM_ORE.get())
//                .add(CMBlocks.RUTHENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RUTHENIUM_ORE.get())
//                .add(CMBlocks.SAMARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SAMARIUM_ORE.get())
//                .add(CMBlocks.SCANDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SCANDIUM_ORE.get())
//                .add(CMBlocks.SELENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SELENIUM_ORE.get())
//                .add(CMBlocks.SILICON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILICON_ORE.get())
//                .add(CMBlocks.SILVER_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILVER_ORE.get())
//                .add(CMBlocks.SODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SODIUM_ORE.get())
//                .add(CMBlocks.STRONTIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_STRONTIUM_ORE.get())
//                .add(CMBlocks.TELLURIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TELLURIUM_ORE.get())
//                .add(CMBlocks.TERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TERBIUM_ORE.get())
//                .add(CMBlocks.THALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THALLIUM_ORE.get())
//                .add(CMBlocks.THORIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THORIUM_ORE.get())
//                .add(CMBlocks.THULIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THULIUM_ORE.get())
//                .add(CMBlocks.TIN_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TIN_ORE.get())
//                .add(CMBlocks.TITANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TITANIUM_ORE.get())
//                .add(CMBlocks.URANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_URANIUM_ORE.get())
//                .add(CMBlocks.VANADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VANADIUM_ORE.get())
//                .add(CMBlocks.VIBRANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VIBRANIUM_ORE.get())
//                .add(CMBlocks.YTTERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTERBIUM_ORE.get())
//                .add(CMBlocks.YTTRIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTRIUM_ORE.get())
//                .add(CMBlocks.ZIRCONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ZIRCONIUM_ORE.get());

        this.tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(CMBlocks.BLUE_EMERALD_BLOCK.get())
                .add(CMBlocks.COBALT_BLOCK.get())
                .add(CMBlocks.COBALT_ORE.get())
                .add(CMBlocks.DEEPSLATE_COBALT_ORE.get())
                .add(CMBlocks.LIGHTNING_BLOCK.get())
                .add(CMBlocks.WHITE_DWARF_STAR_ORE.get())
                .add(CMBlocks.DEEPSLATE_WHITE_DWARF_STAR_ORE.get());


        this.tag(CMBlockTags.RUBY_ORE)
                .add(CMBlocks.RUBY_ORE.get())
                .add(CMBlocks.DEEPSLATE_RUBY_ORE.get())
                .add(CMBlocks.RUBY_ORE_NETHER.get());
        this.tag(CMBlockTags.OPAL_ORE)
                .add(CMBlocks.OPAL_ORE.get())
                .add(CMBlocks.DEEPSLATE_OPAL_ORE.get());
        this.tag(CMBlockTags.TANGERINE_ORE)
                .add(CMBlocks.TANGERINE_ORE.get())
                .add(CMBlocks.DEEPSLATE_TANGERINE_ORE.get());
        this.tag(CMBlockTags.COBALT_ORE)
                .add(CMBlocks.COBALT_ORE.get())
                .add(CMBlocks.DEEPSLATE_COBALT_ORE.get());
        this.tag(CMBlockTags.PARYTH_ORE)
                .add(CMBlocks.PARYTH_ORE.get())
                .add(CMBlocks.DEEPSLATE_PARYTH_ORE.get());
        this.tag(CMBlockTags.WHITE_DWARF_STAR_ORE)
                .add(CMBlocks.WHITE_DWARF_STAR_ORE.get())
                .add(CMBlocks.DEEPSLATE_WHITE_DWARF_STAR_ORE.get());
        this.tag(CMBlockTags.NATURAL_ESSENCE_ORE)
                .add(CMBlocks.NATURAL_ESSENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_NATURAL_ESSENCE_ORE.get());
        this.tag(CMBlockTags.EXPERIENCE_ORE)
                .add(CMBlocks.EXPERIENCE_ORE.get())
                .add(CMBlocks.DEEPSLATE_EXPERIENCE_ORE.get());
//        this.tag(CMBlockTags.ALUMINUM_ORE)
//                .add(CMBlocks.ALUMINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ALUMINUM_ORE.get());
//        this.tag(CMBlockTags.ANTIMONY_ORE)
//                .add(CMBlocks.ANTIMONY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ANTIMONY_ORE.get());
//        this.tag(CMBlockTags.ARSENIC_ORE)
//                .add(CMBlocks.ARSENIC_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ARSENIC_ORE.get());
//        this.tag(CMBlockTags.BARIUM_ORE)
//                .add(CMBlocks.BARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BARIUM_ORE.get());
//        this.tag(CMBlockTags.BERYLLIUM_ORE)
//                .add(CMBlocks.BERYLLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BERYLLIUM_ORE.get());
//        this.tag(CMBlockTags.BISMUTH_ORE)
//                .add(CMBlocks.BISMUTH_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BISMUTH_ORE.get());
//        this.tag(CMBlockTags.BORON_ORE)
//                .add(CMBlocks.BORON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_BORON_ORE.get());
//        this.tag(CMBlockTags.CADMIUM_ORE)
//                .add(CMBlocks.CADMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CADMIUM_ORE.get());
//        this.tag(CMBlockTags.CALCIUM_ORE)
//                .add(CMBlocks.CALCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CALCIUM_ORE.get());
//        this.tag(CMBlockTags.CERIUM_ORE)
//                .add(CMBlocks.CERIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CERIUM_ORE.get());
//        this.tag(CMBlockTags.CESIUM_ORE)
//                .add(CMBlocks.CESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CESIUM_ORE.get());
//        this.tag(CMBlockTags.CHROMIUM_ORE)
//                .add(CMBlocks.CHROMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_CHROMIUM_ORE.get());
//        this.tag(CMBlockTags.DYSPROSIUM_ORE)
//                .add(CMBlocks.DYSPROSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_DYSPROSIUM_ORE.get());
//        this.tag(CMBlockTags.ERBIUM_ORE)
//                .add(CMBlocks.ERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ERBIUM_ORE.get());
//        this.tag(CMBlockTags.EUROPIUM_ORE)
//                .add(CMBlocks.EUROPIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_EUROPIUM_ORE.get());
//        this.tag(CMBlockTags.FRANCIUM_ORE)
//                .add(CMBlocks.FRANCIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_FRANCIUM_ORE.get());
//        this.tag(CMBlockTags.GADOLINIUM_ORE)
//                .add(CMBlocks.GADOLINIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GADOLINIUM_ORE.get());
//        this.tag(CMBlockTags.GALLIUM_ORE)
//                .add(CMBlocks.GALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GALLIUM_ORE.get());
//        this.tag(CMBlockTags.GERMANIUM_ORE)
//                .add(CMBlocks.GERMANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_GERMANIUM_ORE.get());
//        this.tag(CMBlockTags.HAFNIUM_ORE)
//                .add(CMBlocks.HAFNIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HAFNIUM_ORE.get());
//        this.tag(CMBlockTags.HOLMIUM_ORE)
//                .add(CMBlocks.HOLMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_HOLMIUM_ORE.get());
//        this.tag(CMBlockTags.INDIUM_ORE)
//                .add(CMBlocks.INDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_INDIUM_ORE.get());
//        this.tag(CMBlockTags.IRIDIUM_ORE)
//                .add(CMBlocks.IRIDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_IRIDIUM_ORE.get());
//        this.tag(CMBlockTags.LANTHANUM_ORE)
//                .add(CMBlocks.LANTHANUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LANTHANUM_ORE.get());
//        this.tag(CMBlockTags.LEAD_ORE)
//                .add(CMBlocks.LEAD_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LEAD_ORE.get());
//        this.tag(CMBlockTags.LITHIUM_ORE)
//                .add(CMBlocks.LITHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LITHIUM_ORE.get());
//        this.tag(CMBlockTags.LUTETIUM_ORE)
//                .add(CMBlocks.LUTETIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_LUTETIUM_ORE.get());
//        this.tag(CMBlockTags.MAGNESIUM_ORE)
//                .add(CMBlocks.MAGNESIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MAGNESIUM_ORE.get());
//        this.tag(CMBlockTags.MANGANESE_ORE)
//                .add(CMBlocks.MANGANESE_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MANGANESE_ORE.get());
//        this.tag(CMBlockTags.MERCURY_ORE)
//                .add(CMBlocks.MERCURY_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MERCURY_ORE.get());
//        this.tag(CMBlockTags.MYTHRIL_ORE)
//                .add(CMBlocks.MYTHRIL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MYTHRIL_ORE.get());
//        this.tag(CMBlockTags.MOLYBDENUM_ORE)
//                .add(CMBlocks.MOLYBDENUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_MOLYBDENUM_ORE.get());
//        this.tag(CMBlockTags.NEODYMIUM_ORE)
//                .add(CMBlocks.NEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NEODYMIUM_ORE.get());
//        this.tag(CMBlockTags.NICKEL_ORE)
//                .add(CMBlocks.NICKEL_ORE.get())
//                .add(CMBlocks.DEEPSLATE_NICKEL_ORE.get());
//        this.tag(CMBlockTags.OSMIUM_ORE)
//                .add(CMBlocks.OSMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_OSMIUM_ORE.get());
//        this.tag(CMBlockTags.PALLADIUM_ORE)
//                .add(CMBlocks.PALLADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PALLADIUM_ORE.get());
//        this.tag(CMBlockTags.PLATINUM_ORE)
//                .add(CMBlocks.PLATINUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLATINUM_ORE.get());
//        this.tag(CMBlockTags.PLUTONIUM_ORE)
//                .add(CMBlocks.PLUTONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PLUTONIUM_ORE.get());
//        this.tag(CMBlockTags.POLONIUM_ORE)
//                .add(CMBlocks.POLONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POLONIUM_ORE.get());
//        this.tag(CMBlockTags.POTASSIUM_ORE)
//                .add(CMBlocks.POTASSIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_POTASSIUM_ORE.get());
//        this.tag(CMBlockTags.PRASEODYMIUM_ORE)
//                .add(CMBlocks.PRASEODYMIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PRASEODYMIUM_ORE.get());
//        this.tag(CMBlockTags.PROMETHIUM_ORE)
//                .add(CMBlocks.PROMETHIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_PROMETHIUM_ORE.get());
//        this.tag(CMBlockTags.RADIUM_ORE)
//                .add(CMBlocks.RADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RADIUM_ORE.get());
//        this.tag(CMBlockTags.RHODIUM_ORE)
//                .add(CMBlocks.RHODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RHODIUM_ORE.get());
//        this.tag(CMBlockTags.RUTHENIUM_ORE)
//                .add(CMBlocks.RUTHENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_RUTHENIUM_ORE.get());
//        this.tag(CMBlockTags.SAMARIUM_ORE)
//                .add(CMBlocks.SAMARIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SAMARIUM_ORE.get());
//        this.tag(CMBlockTags.SCANDIUM_ORE)
//                .add(CMBlocks.SCANDIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SCANDIUM_ORE.get());
//        this.tag(CMBlockTags.SELENIUM_ORE)
//                .add(CMBlocks.SELENIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SELENIUM_ORE.get());
//        this.tag(CMBlockTags.SILICON_ORE)
//                .add(CMBlocks.SILICON_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILICON_ORE.get());
//        this.tag(CMBlockTags.SILVER_ORE)
//                .add(CMBlocks.SILVER_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SILVER_ORE.get());
//        this.tag(CMBlockTags.SODIUM_ORE)
//                .add(CMBlocks.SODIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_SODIUM_ORE.get());
//        this.tag(CMBlockTags.STRONTIUM_ORE)
//                .add(CMBlocks.STRONTIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_STRONTIUM_ORE.get());
//        this.tag(CMBlockTags.TELLURIUM_ORE)
//                .add(CMBlocks.TELLURIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TELLURIUM_ORE.get());
//        this.tag(CMBlockTags.TERBIUM_ORE)
//                .add(CMBlocks.TERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TERBIUM_ORE.get());
//        this.tag(CMBlockTags.THALLIUM_ORE)
//                .add(CMBlocks.THALLIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THALLIUM_ORE.get());
//        this.tag(CMBlockTags.THORIUM_ORE)
//                .add(CMBlocks.THORIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THORIUM_ORE.get());
//        this.tag(CMBlockTags.THULIUM_ORE)
//                .add(CMBlocks.THULIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_THULIUM_ORE.get());
//        this.tag(CMBlockTags.TIN_ORE)
//                .add(CMBlocks.TIN_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TIN_ORE.get());
//        this.tag(CMBlockTags.TITANIUM_ORE)
//                .add(CMBlocks.TITANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_TITANIUM_ORE.get());
//        this.tag(CMBlockTags.URANIUM_ORE)
//                .add(CMBlocks.URANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_URANIUM_ORE.get());
//        this.tag(CMBlockTags.VANADIUM_ORE)
//                .add(CMBlocks.VANADIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VANADIUM_ORE.get());
//        this.tag(CMBlockTags.VIBRANIUM_ORE)
//                .add(CMBlocks.VIBRANIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_VIBRANIUM_ORE.get());
//        this.tag(CMBlockTags.YTTERBIUM_ORE)
//                .add(CMBlocks.YTTERBIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTERBIUM_ORE.get());
//        this.tag(CMBlockTags.YTTRIUM_ORE)
//                .add(CMBlocks.YTTRIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_YTTRIUM_ORE.get());
//        this.tag(CMBlockTags.ZIRCONIUM_ORE)
//                .add(CMBlocks.ZIRCONIUM_ORE.get())
//                .add(CMBlocks.DEEPSLATE_ZIRCONIUM_ORE.get());
    }

    @Override
    public String getName() {
        return "Block Tags";
    }
}
