package github.cjcj55.chrispymod.datagen;

import github.cjcj55.chrispymod.ChrispyMod;
import github.cjcj55.chrispymod.registry.CMBlocks;
import github.cjcj55.chrispymod.registry.CMItems;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

public class CMLanguageProvider extends LanguageProvider {
    public CMLanguageProvider(PackOutput output, String locale) {
        super(output, ChrispyMod.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add(CMItems.RUBY.get(), "Ruby");
        add(CMItems.RUBY_PICKAXE.get(), "Ruby Pickaxe");
        add(CMItems.RUBY_SWORD.get(), "Ruby Sword");
        add(CMItems.RUBY_AXE.get(), "Ruby Axe");
        add(CMItems.RUBY_SHOVEL.get(), "Ruby Shovel");
        add(CMItems.RUBY_HOE.get(), "Ruby Hoe");
        add(CMItems.RUBY_HELMET.get(), "Ruby Helmet");
        add(CMItems.RUBY_CHESTPLATE.get(), "Ruby Chestplate");
        add(CMItems.RUBY_LEGGINGS.get(), "Ruby Leggings");
        add(CMItems.RUBY_BOOTS.get(), "Ruby Boots");
        add(CMBlocks.RUBY_BLOCK.get(), "Ruby Block");
        add(CMBlocks.RUBY_ORE.get(), "Ruby Ore");
        add(CMBlocks.DEEPSLATE_RUBY_ORE.get(), "Deepslate Ruby Ore");
        add(CMBlocks.RUBY_ORE_NETHER.get(), "Nether Ruby Ore");

        add(CMItems.OPAL.get(), "Opal");
        add(CMItems.OPAL_PICKAXE.get(), "Opal Pickaxe");
        add(CMItems.OPAL_SWORD.get(), "Opal Sword");
        add(CMItems.OPAL_AXE.get(), "Opal Axe");
        add(CMItems.OPAL_SHOVEL.get(), "Opal Shovel");
        add(CMItems.OPAL_HOE.get(), "Opal Hoe");
        add(CMItems.OPAL_HELMET.get(), "Opal Helmet");
        add(CMItems.OPAL_CHESTPLATE.get(), "Opal Chestplate");
        add(CMItems.OPAL_LEGGINGS.get(), "Opal Leggings");
        add(CMItems.OPAL_BOOTS.get(), "Opal Boots");
        add(CMBlocks.OPAL_BLOCK.get(), "Opal Block");
        add(CMBlocks.OPAL_ORE.get(), "Opal Ore");
        add(CMBlocks.DEEPSLATE_OPAL_ORE.get(), "Deepslate Opal Ore");

        add(CMItems.TANGERINE.get(), "Tangerine");
        add(CMItems.TANGERINE_PICKAXE.get(), "Tangerine Pickaxe");
        add(CMItems.TANGERINE_SWORD.get(), "Tangerine Sword");
        add(CMItems.TANGERINE_AXE.get(), "Tangerine Axe");
        add(CMItems.TANGERINE_SHOVEL.get(), "Tangerine Shovel");
        add(CMItems.TANGERINE_HOE.get(), "Tangerine Hoe");
        add(CMItems.TANGERINE_HELMET.get(), "Tangerine Helmet");
        add(CMItems.TANGERINE_CHESTPLATE.get(), "Tangerine Chestplate");
        add(CMItems.TANGERINE_LEGGINGS.get(), "Tangerine Leggings");
        add(CMItems.TANGERINE_BOOTS.get(), "Tangerine Boots");
        add(CMBlocks.TANGERINE_BLOCK.get(), "Tangerine Block");
        add(CMBlocks.TANGERINE_ORE.get(), "Tangerine Ore");
        add(CMBlocks.DEEPSLATE_TANGERINE_ORE.get(), "Deepslate Tangerine Ore");

        add(CMItems.COBALT.get(), "Cobalt");
        add(CMItems.COBALT_PICKAXE.get(), "Cobalt Pickaxe");
        add(CMItems.COBALT_SWORD.get(), "Cobalt Sword");
        add(CMItems.COBALT_AXE.get(), "Cobalt Axe");
        add(CMItems.COBALT_SHOVEL.get(), "Cobalt Shovel");
        add(CMItems.COBALT_HOE.get(), "Cobalt Hoe");
        add(CMItems.COBALT_HELMET.get(), "Cobalt Helmet");
        add(CMItems.COBALT_CHESTPLATE.get(), "Cobalt Chestplate");
        add(CMItems.COBALT_LEGGINGS.get(), "Cobalt Leggings");
        add(CMItems.COBALT_BOOTS.get(), "Cobalt Boots");
        add(CMBlocks.COBALT_BLOCK.get(), "Cobalt Block");
        add(CMBlocks.COBALT_ORE.get(), "Cobalt Ore");
        add(CMBlocks.DEEPSLATE_COBALT_ORE.get(), "Deepslate Cobalt Ore");

        add(CMItems.BLUE_EMERALD.get(), "Blue Emerald");
        add(CMItems.BLUE_EMERALD_PICKAXE.get(), "Blue Emerald Pickaxe");
        add(CMItems.BLUE_EMERALD_SWORD.get(), "Blue Emerald Sword");
        add(CMItems.BLUE_EMERALD_AXE.get(), "Blue Emerald Axe");
        add(CMItems.BLUE_EMERALD_SHOVEL.get(), "Blue Emerald Shovel");
        add(CMItems.BLUE_EMERALD_HOE.get(), "Blue Emerald Hoe");
        add(CMItems.BLUE_EMERALD_HELMET.get(), "Blue Emerald Helmet");
        add(CMItems.BLUE_EMERALD_CHESTPLATE.get(), "Blue Emerald Chestplate");
        add(CMItems.BLUE_EMERALD_LEGGINGS.get(), "Blue Emerald Leggings");
        add(CMItems.BLUE_EMERALD_BOOTS.get(), "Blue Emerald Boots");
        add(CMBlocks.BLUE_EMERALD_BLOCK.get(), "Blue Emerald Block");

        add(CMItems.PARYTH.get(), "Paryth");
        add(CMItems.PARYTH_PICKAXE.get(), "Paryth Pickaxe");
        add(CMItems.PARYTH_SWORD.get(), "Paryth Sword");
        add(CMItems.PARYTH_AXE.get(), "Paryth Axe");
        add(CMItems.PARYTH_SHOVEL.get(), "Paryth Shovel");
        add(CMItems.PARYTH_HOE.get(), "Paryth Hoe");
        add(CMItems.PARYTH_HELMET.get(), "Paryth Helmet");
        add(CMItems.PARYTH_CHESTPLATE.get(), "Paryth Chestplate");
        add(CMItems.PARYTH_LEGGINGS.get(), "Paryth Leggings");
        add(CMItems.PARYTH_BOOTS.get(), "Paryth Boots");
        add(CMBlocks.PARYTH_BLOCK.get(), "Paryth Block");
        add(CMBlocks.PARYTH_ORE.get(), "Paryth Ore");
        add(CMBlocks.DEEPSLATE_PARYTH_ORE.get(), "Deepslate Paryth Ore");

        add(CMItems.LIGHTNING.get(), "§eLightning");
        add(CMItems.LIGHTNING_PICKAXE.get(), "§eLightning Pickaxe");
        add(CMItems.LIGHTNING_SWORD.get(), "§eLightning Sword");
        add(CMItems.LIGHTNING_AXE.get(), "§eLightning Axe");
        add(CMItems.LIGHTNING_SHOVEL.get(), "§eLightning Shovel");
        add(CMItems.LIGHTNING_HOE.get(), "§eLightning Hoe");
        add(CMItems.LIGHTNING_WAND.get(), "§eLightning Wand");
        add(CMItems.LIGHTNING_HELMET.get(), "§eLightning Helmet");
        add(CMItems.LIGHTNING_CHESTPLATE.get(), "§eLightning Chestplate");
        add(CMItems.LIGHTNING_LEGGINGS.get(), "§eLightning Leggings");
        add(CMItems.LIGHTNING_BOOTS.get(), "§eLightning Boots");
        add(CMBlocks.LIGHTNING_BLOCK.get(), "§eLightning Block");

        add(CMItems.FLAME.get(), "§4Flame");
        add(CMItems.FLAME_PICKAXE.get(), "§4Flame Pickaxe");
        add(CMItems.FLAME_SWORD.get(), "§4Flame Sword");
        add(CMItems.FLAME_AXE.get(), "§4Flame Axe");
        add(CMItems.FLAME_SHOVEL.get(), "§4Flame Shovel");
        add(CMItems.FLAME_HOE.get(), "§4Flame Hoe");
        add(CMItems.FLAME_WAND.get(), "§4Flame Wand");
        add(CMItems.FLAME_HELMET.get(), "§4Flame Helmet");
        add(CMItems.FLAME_CHESTPLATE.get(), "§4Flame Chestplate");
        add(CMItems.FLAME_LEGGINGS.get(), "§4Flame Leggings");
        add(CMItems.FLAME_BOOTS.get(), "§4Flame Boots");
        add(CMBlocks.FLAME_BLOCK.get(), "§4Flame Block");
        add(CMBlocks.FLAME_ORE_NETHER.get(), "§4Nether Flame Ore");

        add(CMItems.REDSTONE_INGOT.get(), "Hardened Redstone Ingot");
        add(CMItems.REDSTONE_PICKAXE.get(), "Redstone Pickaxe");
        add(CMItems.REDSTONE_SWORD.get(), "Redstone Sword");
        add(CMItems.REDSTONE_AXE.get(), "Redstone Axe");
        add(CMItems.REDSTONE_SHOVEL.get(), "Redstone Shovel");
        add(CMItems.REDSTONE_HOE.get(), "Redstone Hoe");
        add(CMItems.REDSTONE_HELMET.get(), "Redstone Helmet");
        add(CMItems.REDSTONE_CHESTPLATE.get(), "Redstone Chestplate");
        add(CMItems.REDSTONE_LEGGINGS.get(), "Redstone Leggings");
        add(CMItems.REDSTONE_BOOTS.get(), "Redstone Boots");
        add(CMBlocks.HARDENED_REDSTONE_BLOCK.get(), "Hardened Redstone Block");

        add(CMItems.EMERALD_PICKAXE.get(), "Emerald Pickaxe");
        add(CMItems.EMERALD_SWORD.get(), "Emerald Sword");
        add(CMItems.EMERALD_AXE.get(), "Emerald Axe");
        add(CMItems.EMERALD_SHOVEL.get(), "Emerald Shovel");
        add(CMItems.EMERALD_HOE.get(), "Emerald Hoe");
        add(CMItems.EMERALD_HELMET.get(), "Emerald Helmet");
        add(CMItems.EMERALD_CHESTPLATE.get(), "Emerald Chestplate");
        add(CMItems.EMERALD_LEGGINGS.get(), "Emerald Leggings");
        add(CMItems.EMERALD_BOOTS.get(), "Emerald Boots");

        add(CMItems.HONEY_STICK.get(), "§6Honey Stick");
        add(CMItems.HONEY_PICKAXE.get(), "§6Honey Pickaxe");
        add(CMItems.HONEY_SWORD.get(), "§6Honey Sword");
        add(CMItems.HONEY_AXE.get(), "§6Honey Axe");
        add(CMItems.HONEY_SHOVEL.get(), "§6Honey Shovel");
        add(CMItems.HONEY_HOE.get(), "§6Honey Hoe");
        add(CMItems.HONEY_HELMET.get(), "§6Honey Helmet");
        add(CMItems.HONEY_CHESTPLATE.get(), "§6Honey Chestplate");
        add(CMItems.HONEY_LEGGINGS.get(), "§6Honey Leggings");
        add(CMItems.HONEY_BOOTS.get(), "§6Honey Boots");

        add(CMItems.WHITE_DWARF_STAR.get(), "White Dwarf Star");
        add(CMItems.WHITE_DWARF_STAR_HELMET.get(), "White Dwarf Star Helmet");
        add(CMItems.WHITE_DWARF_STAR_CHESTPLATE.get(), "White Dwarf Star Chestplate");
        add(CMItems.WHITE_DWARF_STAR_LEGGINGS.get(), "White Dwarf Star Leggings");
        add(CMItems.WHITE_DWARF_STAR_BOOTS.get(), "White Dwarf Star Boots");
        add(CMBlocks.WHITE_DWARF_STAR_ORE.get(), "White Dwarf Star Ore");
        add(CMBlocks.DEEPSLATE_WHITE_DWARF_STAR_ORE.get(), "Deepslate White Dwarf Star Ore");

        add(CMBlocks.NATURAL_ESSENCE_ORE.get(), "Natural Essence Ore");
        add(CMBlocks.DEEPSLATE_NATURAL_ESSENCE_ORE.get(), "Deepslate Natural Essence Ore");
        add(CMItems.NATURAL_ESSENCE.get(), "Natural Essence");

        add(CMBlocks.EXPERIENCE_ORE.get(), "Experience Ore");
        add(CMBlocks.DEEPSLATE_EXPERIENCE_ORE.get(), "Deepslate Experience Ore");
        add(CMItems.EDIBLE_EXPERIENCE.get(), "§2Edible Experience");

        add(CMBlocks.HELLFIRE_ORE_NETHER.get(), "Hellfire Ore");
        add(CMItems.HELLFIRE.get(), "Hellfire");

//        add(CMBlocks.ALUMINUM_ORE.get(), "Aluminum Ore");
//        add(CMBlocks.DEEPSLATE_ALUMINUM_ORE.get(), "Deepslate Aluminum Ore");
//        add(CMBlocks.ANTIMONY_ORE.get(), "Antimony Ore");
//        add(CMBlocks.DEEPSLATE_ANTIMONY_ORE.get(), "Deepslate Antimony Ore");
//        add(CMBlocks.ARSENIC_ORE.get(), "Arsenic Ore");
//        add(CMBlocks.DEEPSLATE_ARSENIC_ORE.get(), "Deepslate Arsenic Ore");
//        add(CMBlocks.BARIUM_ORE.get(), "Barium Ore");
//        add(CMBlocks.DEEPSLATE_BARIUM_ORE.get(), "Deepslate Barium Ore");
//        add(CMBlocks.BERYLLIUM_ORE.get(), "Beryllium Ore");
//        add(CMBlocks.DEEPSLATE_BERYLLIUM_ORE.get(), "Deepslate Beryllium Ore");
//        add(CMBlocks.BISMUTH_ORE.get(), "Bismuth Ore");
//        add(CMBlocks.DEEPSLATE_BISMUTH_ORE.get(), "Deepslate Bismuth Ore");
//        add(CMBlocks.BORON_ORE.get(), "Boron Ore");
//        add(CMBlocks.DEEPSLATE_BORON_ORE.get(), "Deepslate Boron Ore");
//        add(CMBlocks.CADMIUM_ORE.get(), "Cadmium Ore");
//        add(CMBlocks.DEEPSLATE_CADMIUM_ORE.get(), "Deepslate Cadmium Ore");
//        add(CMBlocks.CALCIUM_ORE.get(), "Calcium Ore");
//        add(CMBlocks.DEEPSLATE_CALCIUM_ORE.get(), "Deepslate Calcium Ore");
//        add(CMBlocks.CERIUM_ORE.get(), "Cerium Ore");
//        add(CMBlocks.DEEPSLATE_CERIUM_ORE.get(), "Deepslate Cerium Ore");
//        add(CMBlocks.CESIUM_ORE.get(), "Cesium Ore");
//        add(CMBlocks.DEEPSLATE_CESIUM_ORE.get(), "Deepslate Cesium Ore");
//        add(CMBlocks.CHROMIUM_ORE.get(), "Chromium Ore");
//        add(CMBlocks.DEEPSLATE_CHROMIUM_ORE.get(), "Deepslate Chromium Ore");
//        add(CMBlocks.DYSPROSIUM_ORE.get(), "Dysprosium Ore");
//        add(CMBlocks.DEEPSLATE_DYSPROSIUM_ORE.get(), "Deepslate Dysprosium Ore");
//        add(CMBlocks.ERBIUM_ORE.get(), "Erbium Ore");
//        add(CMBlocks.DEEPSLATE_ERBIUM_ORE.get(), "Deepslate Erbium Ore");
//        add(CMBlocks.EUROPIUM_ORE.get(), "Europium Ore");
//        add(CMBlocks.DEEPSLATE_EUROPIUM_ORE.get(), "Deepslate Europium Ore");
//        add(CMBlocks.FRANCIUM_ORE.get(), "Francium Ore");
//        add(CMBlocks.DEEPSLATE_FRANCIUM_ORE.get(), "Deepslate Francium Ore");
//        add(CMBlocks.GADOLINIUM_ORE.get(), "Gadolinium Ore");
//        add(CMBlocks.DEEPSLATE_GADOLINIUM_ORE.get(), "Deepslate Gadolinium Ore");
//        add(CMBlocks.GALLIUM_ORE.get(), "Gallium Ore");
//        add(CMBlocks.DEEPSLATE_GALLIUM_ORE.get(), "Deepslate Gallium Ore");
//        add(CMBlocks.GERMANIUM_ORE.get(), "Germanium Ore");
//        add(CMBlocks.DEEPSLATE_GERMANIUM_ORE.get(), "Deepslate Germanium Ore");
//        add(CMBlocks.HAFNIUM_ORE.get(), "Hafnium Ore");
//        add(CMBlocks.DEEPSLATE_HAFNIUM_ORE.get(), "Deepslate Hafnium Ore");
//        add(CMBlocks.HOLMIUM_ORE.get(), "Holmium Ore");
//        add(CMBlocks.DEEPSLATE_HOLMIUM_ORE.get(), "Deepslate Holmium Ore");
//        add(CMBlocks.INDIUM_ORE.get(), "Indium Ore");
//        add(CMBlocks.DEEPSLATE_INDIUM_ORE.get(), "Deepslate Indium Ore");
//        add(CMBlocks.IRIDIUM_ORE.get(), "Iridium Ore");
//        add(CMBlocks.DEEPSLATE_IRIDIUM_ORE.get(), "Deepslate Iridium Ore");
//        add(CMBlocks.LANTHANUM_ORE.get(), "Lanthanum Ore");
//        add(CMBlocks.DEEPSLATE_LANTHANUM_ORE.get(), "Deepslate Lanthanum Ore");
//        add(CMBlocks.LEAD_ORE.get(), "Lead Ore");
//        add(CMBlocks.DEEPSLATE_LEAD_ORE.get(), "Deepslate Lead Ore");
//        add(CMBlocks.LITHIUM_ORE.get(), "Lithium Ore");
//        add(CMBlocks.DEEPSLATE_LITHIUM_ORE.get(), "Deepslate Lithium Ore");
//        add(CMBlocks.LUTETIUM_ORE.get(), "Lutetium Ore");
//        add(CMBlocks.DEEPSLATE_LUTETIUM_ORE.get(), "Deepslate Lutetium Ore");
//        add(CMBlocks.MAGNESIUM_ORE.get(), "Magnesium Ore");
//        add(CMBlocks.DEEPSLATE_MAGNESIUM_ORE.get(), "Deepslate Magnesium Ore");
//        add(CMBlocks.MANGANESE_ORE.get(), "Manganese Ore");
//        add(CMBlocks.DEEPSLATE_MANGANESE_ORE.get(), "Deepslate Manganeses Ore");
//        add(CMBlocks.MERCURY_ORE.get(), "Mercury Ore");
//        add(CMBlocks.DEEPSLATE_MERCURY_ORE.get(), "Deepslate Mercury Ore");
//        add(CMBlocks.MYTHRIL_ORE.get(), "Mythril Ore");
//        add(CMBlocks.DEEPSLATE_MYTHRIL_ORE.get(), "Deepslate Mythril Ore");
//        add(CMBlocks.MOLYBDENUM_ORE.get(), "Molybdenum Ore");
//        add(CMBlocks.DEEPSLATE_MOLYBDENUM_ORE.get(), "Deepslate Molybdenum Ore");
//        add(CMBlocks.NEODYMIUM_ORE.get(), "Neodymium Ore");
//        add(CMBlocks.DEEPSLATE_NEODYMIUM_ORE.get(), "Deepslate Neodymium Ore");
//        add(CMBlocks.NICKEL_ORE.get(), "Nickel Ore");
//        add(CMBlocks.DEEPSLATE_NICKEL_ORE.get(), "Deepslate Nickel Ore");
//        add(CMBlocks.OSMIUM_ORE.get(), "Osmium Ore");
//        add(CMBlocks.DEEPSLATE_OSMIUM_ORE.get(), "Deepslate Osmium Ore");
//        add(CMBlocks.PALLADIUM_ORE.get(), "Palladium Ore");
//        add(CMBlocks.DEEPSLATE_PALLADIUM_ORE.get(), "Deepslate Palladium Ore");
//        add(CMBlocks.PLATINUM_ORE.get(), "Platinum Ore");
//        add(CMBlocks.DEEPSLATE_PLATINUM_ORE.get(), "Deepslate Platinum Ore");
//        add(CMBlocks.PLUTONIUM_ORE.get(), "Plutonium Ore");
//        add(CMBlocks.DEEPSLATE_PLUTONIUM_ORE.get(), "Deepslate Plutonium Ore");
//        add(CMBlocks.POLONIUM_ORE.get(), "Polonium Ore");
//        add(CMBlocks.DEEPSLATE_POLONIUM_ORE.get(), "Deepslate Polonium Ore");
//        add(CMBlocks.POTASSIUM_ORE.get(), "Potassium Ore");
//        add(CMBlocks.DEEPSLATE_POTASSIUM_ORE.get(), "Deepslate Potassium Ore");
//        add(CMBlocks.PRASEODYMIUM_ORE.get(), "Praseodymium Ore");
//        add(CMBlocks.DEEPSLATE_PRASEODYMIUM_ORE.get(), "Deepslate Praseodymium Ore");
//        add(CMBlocks.PROMETHIUM_ORE.get(), "Promethium Ore");
//        add(CMBlocks.DEEPSLATE_PROMETHIUM_ORE.get(), "Deepslate Promethium Ore");
//        add(CMBlocks.RADIUM_ORE.get(), "Radium Ore");
//        add(CMBlocks.DEEPSLATE_RADIUM_ORE.get(), "Deepslate Radium Ore");
//        add(CMBlocks.RHODIUM_ORE.get(), "Rhodium Ore");
//        add(CMBlocks.DEEPSLATE_RHODIUM_ORE.get(), "Deepslate Rhodium Ore");
//        add(CMBlocks.RUTHENIUM_ORE.get(), "Ruthenium Ore");
//        add(CMBlocks.DEEPSLATE_RUTHENIUM_ORE.get(), "Deepslate Ruthenium Ore");
//        add(CMBlocks.SAMARIUM_ORE.get(), "Samarium Ore");
//        add(CMBlocks.DEEPSLATE_SAMARIUM_ORE.get(), "Deepslate Samarium Ore");
//        add(CMBlocks.SCANDIUM_ORE.get(), "Scandium Ore");
//        add(CMBlocks.DEEPSLATE_SCANDIUM_ORE.get(), "Deepslate Scandium Ore");
//        add(CMBlocks.SELENIUM_ORE.get(), "Selenium Ore");
//        add(CMBlocks.DEEPSLATE_SELENIUM_ORE.get(), "Deepslate Selenium Ore");
//        add(CMBlocks.SILICON_ORE.get(), "Silicon Ore");
//        add(CMBlocks.DEEPSLATE_SILICON_ORE.get(), "Deepslate Silicon Ore");
//        add(CMBlocks.SILVER_ORE.get(), "Silver Ore");
//        add(CMBlocks.DEEPSLATE_SILVER_ORE.get(), "Deepslate Silver Ore");
//        add(CMBlocks.SODIUM_ORE.get(), "Sodium Ore");
//        add(CMBlocks.DEEPSLATE_SODIUM_ORE.get(), "Deepslate Sodium Ore");
//        add(CMBlocks.STRONTIUM_ORE.get(), "Strontium Ore");
//        add(CMBlocks.DEEPSLATE_STRONTIUM_ORE.get(), "Deepslate Strontium Ore");
//        add(CMBlocks.TELLURIUM_ORE.get(), "Tellurium Ore");
//        add(CMBlocks.DEEPSLATE_TELLURIUM_ORE.get(), "Deepslate Tellurium Ore");
//        add(CMBlocks.TERBIUM_ORE.get(), "Terbium Ore");
//        add(CMBlocks.DEEPSLATE_TERBIUM_ORE.get(), "Deepslate Terbium Ore");
//        add(CMBlocks.THALLIUM_ORE.get(), "Thallium Ore");
//        add(CMBlocks.DEEPSLATE_THALLIUM_ORE.get(), "Deepslate Thallium Ore");
//        add(CMBlocks.THORIUM_ORE.get(), "Thorium Ore");
//        add(CMBlocks.DEEPSLATE_THORIUM_ORE.get(), "Deepslate Thorium Ore");
//        add(CMBlocks.THULIUM_ORE.get(), "Thulium Ore");
//        add(CMBlocks.DEEPSLATE_THULIUM_ORE.get(), "Deepslate Thulium Ore");
//        add(CMBlocks.TIN_ORE.get(), "Tin Ore");
//        add(CMBlocks.DEEPSLATE_TIN_ORE.get(), "Deepslate Tin Ore");
//        add(CMBlocks.TITANIUM_ORE.get(), "Titanium Ore");
//        add(CMBlocks.DEEPSLATE_TITANIUM_ORE.get(), "Deepslate Titanium Ore");
//        add(CMBlocks.URANIUM_ORE.get(), "Uranium Ore");
//        add(CMBlocks.DEEPSLATE_URANIUM_ORE.get(), "Deepslate Uranium Ore");
//        add(CMBlocks.VANADIUM_ORE.get(), "Vanadium Ore");
//        add(CMBlocks.DEEPSLATE_VANADIUM_ORE.get(), "Deepslate Vanadium Ore");
//        add(CMBlocks.VIBRANIUM_ORE.get(), "Vibranium Ore");
//        add(CMBlocks.DEEPSLATE_VIBRANIUM_ORE.get(), "Deepslate Vibranium Ore");
//        add(CMBlocks.YTTERBIUM_ORE.get(), "Ytterbium Ore");
//        add(CMBlocks.DEEPSLATE_YTTERBIUM_ORE.get(), "Deepslate Ytterbium Ore");
//        add(CMBlocks.YTTRIUM_ORE.get(), "Yttrium Ore");
//        add(CMBlocks.DEEPSLATE_YTTRIUM_ORE.get(), "Deepslate Yttrium Ore");
//        add(CMBlocks.ZIRCONIUM_ORE.get(), "Zirconium Ore");
//        add(CMBlocks.DEEPSLATE_ZIRCONIUM_ORE.get(), "Deepslate Zirconium Ore");

//        add(CMItems.ALUMINUM.get(), "Aluminum");
//        add(CMItems.RAW_ALUMINUM.get(), "Raw Aluminum");
//        add(CMItems.ANTIMONY.get(), "Antimony");
//        add(CMItems.RAW_ANTIMONY.get(), "Raw Antimony");
//        add(CMItems.ARSENIC.get(), "Arsenic");
//        add(CMItems.RAW_ARSENIC.get(), "Raw Arsenic");
//        add(CMItems.BARIUM.get(), "Barium");
//        add(CMItems.RAW_BARIUM.get(), "Raw Barium");
//        add(CMItems.BERYLLIUM.get(), "Beryllium");
//        add(CMItems.RAW_BERYLLIUM.get(), "Raw Beryllium");
//        add(CMItems.BISMUTH.get(), "Bismuth");
//        add(CMItems.RAW_BISMUTH.get(), "Raw Bismuth");
//        add(CMItems.BORON.get(), "Boron");
//        add(CMItems.RAW_BORON.get(), "Raw Boron");
//        add(CMItems.CADMIUM.get(), "Cadmium");
//        add(CMItems.RAW_CADMIUM.get(), "Raw Cadmium");
//        add(CMItems.CALCIUM.get(), "Calcium");
//        add(CMItems.RAW_CALCIUM.get(), "Raw Calcium");
//        add(CMItems.CERIUM.get(), "Cerium");
//        add(CMItems.RAW_CERIUM.get(), "Raw Cerium");
//        add(CMItems.CESIUM.get(), "Cesium");
//        add(CMItems.RAW_CESIUM.get(), "Raw Cesium");
//        add(CMItems.CHROMIUM.get(), "Chromium");
//        add(CMItems.RAW_CHROMIUM.get(), "Raw Chromium");
//        add(CMItems.DYSPROSIUM.get(), "Dysprosium");
//        add(CMItems.RAW_DYSPROSIUM.get(), "Raw Dysprosium");
//        add(CMItems.ERBIUM.get(), "Erbium");
//        add(CMItems.RAW_ERBIUM.get(), "Raw Erbium");
//        add(CMItems.EUROPIUM.get(), "Europium");
//        add(CMItems.RAW_EUROPIUM.get(), "Raw Europium");
//        add(CMItems.FRANCIUM.get(), "Francium");
//        add(CMItems.RAW_FRANCIUM.get(), "Raw Francium");
//        add(CMItems.GADOLINIUM.get(), "Gadolinium");
//        add(CMItems.RAW_GADOLINIUM.get(), "Raw Gadolinium");
//        add(CMItems.GALLIUM.get(), "Gallium");
//        add(CMItems.RAW_GALLIUM.get(), "Raw Gallium");
//        add(CMItems.GERMANIUM.get(), "Germanium");
//        add(CMItems.RAW_GERMANIUM.get(), "Raw Germanium");
//        add(CMItems.HAFNIUM.get(), "Hafnium");
//        add(CMItems.RAW_HAFNIUM.get(), "Raw Hafnium");
//        add(CMItems.HOLMIUM.get(), "Holmium");
//        add(CMItems.RAW_HOLMIUM.get(), "Raw Holmium");
//        add(CMItems.INDIUM.get(), "Indium");
//        add(CMItems.RAW_INDIUM.get(), "Raw Indium");
//        add(CMItems.IRIDIUM.get(), "Iridium");
//        add(CMItems.RAW_IRIDIUM.get(), "Raw Iridium");
//        add(CMItems.LANTHANUM.get(), "Lanthanum");
//        add(CMItems.RAW_LANTHANUM.get(), "Raw Lanthanum");
//        add(CMItems.LEAD.get(), "Lead");
//        add(CMItems.RAW_LEAD.get(), "Raw Lead");
//        add(CMItems.LITHIUM.get(), "Lithium");
//        add(CMItems.RAW_LITHIUM.get(), "Raw Lithium");
//        add(CMItems.LUTETIUM.get(), "Lutetium");
//        add(CMItems.RAW_LUTETIUM.get(), "Raw Lutetium");
//        add(CMItems.MAGNESIUM.get(), "Magnesium");
//        add(CMItems.RAW_MAGNESIUM.get(), "Raw Magnesium");
//        add(CMItems.MANGANESE.get(), "Manganese");
//        add(CMItems.RAW_MANGANESE.get(), "Raw Manganeses");
//        add(CMItems.MERCURY.get(), "Mercury");
//        add(CMItems.RAW_MERCURY.get(), "Raw Mercury");
//        add(CMItems.MYTHRIL.get(), "Mythril");
//        add(CMItems.RAW_MYTHRIL.get(), "Raw Mythril");
//        add(CMItems.MOLYBDENUM.get(), "Molybdenum");
//        add(CMItems.RAW_MOLYBDENUM.get(), "Raw Molybdenum");
//        add(CMItems.NEODYMIUM.get(), "Neodymium");
//        add(CMItems.RAW_NEODYMIUM.get(), "Raw Neodymium");
//        add(CMItems.NICKEL.get(), "Nickel");
//        add(CMItems.RAW_NICKEL.get(), "Raw Nickel");
//        add(CMItems.OSMIUM.get(), "Osmium");
//        add(CMItems.RAW_OSMIUM.get(), "Raw Osmium");
//        add(CMItems.PALLADIUM.get(), "Palladium");
//        add(CMItems.RAW_PALLADIUM.get(), "Raw Palladium");
//        add(CMItems.PLATINUM.get(), "Platinum");
//        add(CMItems.RAW_PLATINUM.get(), "Raw Platinum");
//        add(CMItems.PLUTONIUM.get(), "Plutonium");
//        add(CMItems.RAW_PLUTONIUM.get(), "Raw Plutonium");
//        add(CMItems.POLONIUM.get(), "Polonium");
//        add(CMItems.RAW_POLONIUM.get(), "Raw Polonium");
//        add(CMItems.POTASSIUM.get(), "Potassium");
//        add(CMItems.RAW_POTASSIUM.get(), "Raw Potassium");
//        add(CMItems.PRASEODYMIUM.get(), "Praseodymium");
//        add(CMItems.RAW_PRASEODYMIUM.get(), "Raw Praseodymium");
//        add(CMItems.PROMETHIUM.get(), "Promethium");
//        add(CMItems.RAW_PROMETHIUM.get(), "Raw Promethium");
//        add(CMItems.RADIUM.get(), "Radium");
//        add(CMItems.RAW_RADIUM.get(), "Raw Radium");
//        add(CMItems.RHODIUM.get(), "Rhodium");
//        add(CMItems.RAW_RHODIUM.get(), "Raw Rhodium");
//        add(CMItems.RUTHENIUM.get(), "Ruthenium");
//        add(CMItems.RAW_RUTHENIUM.get(), "Raw Ruthenium");
//        add(CMItems.SAMARIUM.get(), "Samarium");
//        add(CMItems.RAW_SAMARIUM.get(), "Raw Samarium");
//        add(CMItems.SCANDIUM.get(), "Scandium");
//        add(CMItems.RAW_SCANDIUM.get(), "Raw Scandium");
//        add(CMItems.SELENIUM.get(), "Selenium");
//        add(CMItems.RAW_SELENIUM.get(), "Raw Selenium");
//        add(CMItems.SILICON.get(), "Silicon");
//        add(CMItems.RAW_SILICON.get(), "Raw Silicon");
//        add(CMItems.SILVER.get(), "Silver");
//        add(CMItems.RAW_SILVER.get(), "Raw Silver");
//        add(CMItems.SODIUM.get(), "Sodium");
//        add(CMItems.RAW_SODIUM.get(), "Raw Sodium");
//        add(CMItems.STRONTIUM.get(), "Strontium");
//        add(CMItems.RAW_STRONTIUM.get(), "Raw Strontium");
//        add(CMItems.TELLURIUM.get(), "Tellurium");
//        add(CMItems.RAW_TELLURIUM.get(), "Raw Tellurium");
//        add(CMItems.TERBIUM.get(), "Terbium");
//        add(CMItems.RAW_TERBIUM.get(), "Raw Terbium");
//        add(CMItems.THALLIUM.get(), "Thallium");
//        add(CMItems.RAW_THALLIUM.get(), "Raw Thallium");
//        add(CMItems.THORIUM.get(), "Thorium");
//        add(CMItems.RAW_THORIUM.get(), "Raw Thorium");
//        add(CMItems.THULIUM.get(), "Thulium");
//        add(CMItems.RAW_THULIUM.get(), "Raw Thulium");
//        add(CMItems.TIN.get(), "Tin");
//        add(CMItems.RAW_TIN.get(), "Raw Tin");
//        add(CMItems.TITANIUM.get(), "Titanium");
//        add(CMItems.RAW_TITANIUM.get(), "Raw Titanium");
//        add(CMItems.URANIUM.get(), "Uranium");
//        add(CMItems.RAW_URANIUM.get(), "Raw Uranium");
//        add(CMItems.VANADIUM.get(), "Vanadium");
//        add(CMItems.RAW_VANADIUM.get(), "Raw Vanadium");
//        add(CMItems.VIBRANIUM.get(), "Vibranium");
//        add(CMItems.RAW_VIBRANIUM.get(), "Raw Vibranium");
//        add(CMItems.YTTERBIUM.get(), "Ytterbium");
//        add(CMItems.RAW_YTTERBIUM.get(), "Raw Ytterbium");
//        add(CMItems.YTTRIUM.get(), "Yttrium");
//        add(CMItems.RAW_YTTRIUM.get(), "Raw Yttrium");
//        add(CMItems.ZIRCONIUM.get(), "Zirconium");
//        add(CMItems.RAW_ZIRCONIUM.get(), "Raw Zirconium");

        add(CMItems.COOKED_CARROT.get(), "Cooked Carrot");
        add(CMItems.BLACK_CANDY_CANE.get(), "Black Candy Cane");
        add(CMItems.BLUE_CANDY_CANE.get(), "Blue Candy Cane");
        add(CMItems.BROWN_CANDY_CANE.get(), "Brown Candy Cane");
        add(CMItems.CYAN_CANDY_CANE.get(), "Cyan Candy Cane");
        add(CMItems.GRAY_CANDY_CANE.get(), "Gray Candy Cane");
        add(CMItems.GREEN_CANDY_CANE.get(), "Green Candy Cane");
        add(CMItems.LIGHT_BLUE_CANDY_CANE.get(), "Light Blue Candy Cane");
        add(CMItems.LIGHT_GRAY_CANDY_CANE.get(), "Light Gray Candy Cane");
        add(CMItems.LIME_CANDY_CANE.get(), "Lime Candy Cane");
        add(CMItems.MAGENTA_CANDY_CANE.get(), "Magenta Candy Cane");
        add(CMItems.ORANGE_CANDY_CANE.get(), "Orange Candy Cane");
        add(CMItems.PINK_CANDY_CANE.get(), "Pink Candy Cane");
        add(CMItems.PURPLE_CANDY_CANE.get(), "Purple Candy Cane");
        add(CMItems.RED_CANDY_CANE.get(), "Red Candy Cane");
        add(CMItems.WHITE_CANDY_CANE.get(), "White Candy Cane");
        add(CMItems.YELLOW_CANDY_CANE.get(), "Yellow Candy Cane");

        add(CMItems.STRAWBERRY.get(), "Strawberry");
        add(CMItems.BLUEBERRY.get(), "Blueberry");
        add(CMItems.LOGANBERRY.get(), "Loganberry");
        add(CMItems.RED_RASPBERRY.get(), "Red Raspberry");
        add(CMItems.BLACK_RASPBERRY.get(), "Black Raspberry");
        add(CMItems.GOLDEN_RASPBERRY.get(), "Golden Raspberry");
        add(CMItems.WHITE_RASPBERRY.get(), "White Raspberry");
        add(CMItems.MARIONBERRY.get(), "Marionberry");
        add(CMItems.BLACKCURRANT.get(), "Blackcurrant");
        add(CMItems.REDCURRANT.get(), "Redcurrant");
        add(CMItems.HUCKLEBERRY.get(), "Huckleberry");
        add(CMItems.WINEBERRY.get(), "Wineberry");
        add(CMItems.ELDERBERRY.get(), "Elderberry");
        add(CMItems.BLACKBERRY.get(), "Blackberry");
        add(CMItems.BOYSENBERRY.get(), "Boysenberry");
        add(CMItems.GROUND_CHERRY.get(), "Ground Cherry");
        add(CMItems.ARONIA_BERRY.get(), "Aronia Berry");
        add(CMItems.SERVICEBERRY.get(), "Serviceberry");
        add(CMItems.WONDERBERRY.get(), "Wonderberry");
        add(CMItems.MULBERRY.get(), "Mulberry");
        add(CMItems.LINGONBERRY.get(), "Lingonberry");
        add(CMItems.CRANBERRY.get(), "Cranberry");
        add(CMItems.DEWBERRY.get(), "Dewberry");
        add(CMItems.THIMBLEBERRY.get(), "Thimbleberry");
        add(CMItems.GOOSEBERRY.get(), "Gooseberry");
        add(CMItems.CHOKEBERRY.get(), "Chokeberry");
        add(CMItems.OLALLIEBERRY.get(), "Olallieberry");
        add(CMItems.ACEROLA_CHERRY.get(), "Acerola Cherry");
        add(CMItems.BARBERRY.get(), "Barberry");
        add(CMItems.BAYBERRY.get(), "Bayberry");
        add(CMItems.GOGI_BERRY.get(), "Gogi Berry");

        add(CMItems.STRAWBERRY_JAM.get(), "Strawberry Jam");
        add(CMItems.BLUEBERRY_JAM.get(), "Blueberry Jam");
        add(CMItems.LOGANBERRY_JAM.get(), "Loganberry Jam");
        add(CMItems.RED_RASPBERRY_JAM.get(), "Red Raspberry Jam");
        add(CMItems.BLACK_RASPBERRY_JAM.get(), "Black Raspberry Jam");
        add(CMItems.GOLDEN_RASPBERRY_JAM.get(), "Golden Raspberry Jam");
        add(CMItems.WHITE_RASPBERRY_JAM.get(), "White Raspberry Jam");
        add(CMItems.MARIONBERRY_JAM.get(), "Marionberry Jam");
        add(CMItems.BLACKCURRANT_JAM.get(), "Blackcurrant Jam");
        add(CMItems.REDCURRANT_JAM.get(), "Redcurrant Jam");
        add(CMItems.HUCKLEBERRY_JAM.get(), "Huckleberry Jam");
        add(CMItems.WINEBERRY_JAM.get(), "Wineberry Jam");
        add(CMItems.ELDERBERRY_JAM.get(), "Elderberry Jam");
        add(CMItems.BLACKBERRY_JAM.get(), "Blackberry Jam");
        add(CMItems.BOYSENBERRY_JAM.get(), "Boysenberry Jam");
        add(CMItems.GROUND_CHERRY_JAM.get(), "Ground Cherry Jam");
        add(CMItems.ARONIA_BERRY_JAM.get(), "Aronia Berry Jam");
        add(CMItems.SERVICEBERRY_JAM.get(), "Serviceberry Jam");
        add(CMItems.WONDERBERRY_JAM.get(), "Wonderberry Jam");
        add(CMItems.MULBERRY_JAM.get(), "Mulberry Jam");
        add(CMItems.LINGONBERRY_JAM.get(), "Lingonberry Jam");
        add(CMItems.CRANBERRY_JAM.get(), "Cranberry Jam");
        add(CMItems.DEWBERRY_JAM.get(), "Dewberry Jam");
        add(CMItems.THIMBLEBERRY_JAM.get(), "Thimbleberry Jam");
        add(CMItems.GOOSEBERRY_JAM.get(), "Gooseberry Jam");
        add(CMItems.CHOKEBERRY_JAM.get(), "Chokeberry Jam");
        add(CMItems.OLALLIEBERRY_JAM.get(), "Olallieberry Jam");
        add(CMItems.ACEROLA_CHERRY_JAM.get(), "Acerola Cherry Jam");
        add(CMItems.BARBERRY_JAM.get(), "Barberry Jam");
        add(CMItems.BAYBERRY_JAM.get(), "Bayberry Jam");
        add(CMItems.GOGI_BERRY_JAM.get(), "Gogi Berry Jam");

        add(CMBlocks.STRAWBERRY_BUSH.get(), "Strawberry Bush");
        add(CMBlocks.BLUEBERRY_BUSH.get(), "Blueberry Bush");
        add(CMBlocks.LOGANBERRY_BUSH.get(), "Loganberry Bush");
        add(CMBlocks.RED_RASPBERRY_BUSH.get(), "Red Raspberry Bush");
        add(CMBlocks.BLACK_RASPBERRY_BUSH.get(), "Black Raspberry Bush");
        add(CMBlocks.GOLDEN_RASPBERRY_BUSH.get(), "Golden Raspberry Bush");
        add(CMBlocks.WHITE_RASPBERRY_BUSH.get(), "White Raspberry Bush");
        add(CMBlocks.MARIONBERRY_BUSH.get(), "Marionberry Bush");
        add(CMBlocks.BLACKCURRANT_BUSH.get(), "Blackcurrant Bush");
        add(CMBlocks.REDCURRANT_BUSH.get(), "Redcurrant Bush");
        add(CMBlocks.HUCKLEBERRY_BUSH.get(), "Huckleberry Bush");
        add(CMBlocks.WINEBERRY_BUSH.get(), "Wineberry Bush");
        add(CMBlocks.ELDERBERRY_BUSH.get(), "Elderberry Bush");
        add(CMBlocks.BLACKBERRY_BUSH.get(), "Blackberry Bush");
        add(CMBlocks.BOYSENBERRY_BUSH.get(), "Boysenberry Bush");
        add(CMBlocks.GROUND_CHERRY_BUSH.get(), "Ground Cherry Bush");
        add(CMBlocks.ARONIA_BERRY_BUSH.get(), "Aronia Berry Bush");
        add(CMBlocks.SERVICEBERRY_BUSH.get(), "Serviceberry Bush");
        add(CMBlocks.WONDERBERRY_BUSH.get(), "Wonderberry Bush");
        add(CMBlocks.MULBERRY_BUSH.get(), "Mulberry Bush");
        add(CMBlocks.LINGONBERRY_BUSH.get(), "Lingonberry Bush");
        add(CMBlocks.CRANBERRY_BUSH.get(), "Cranberry Bush");
        add(CMBlocks.DEWBERRY_BUSH.get(), "Dewberry Bush");
        add(CMBlocks.THIMBLEBERRY_BUSH.get(), "Thimbleberry Bush");
        add(CMBlocks.GOOSEBERRY_BUSH.get(), "Gooseberry Bush");
        add(CMBlocks.CHOKEBERRY_BUSH.get(), "Chokeberry Bush");
        add(CMBlocks.OLALLIEBERRY_BUSH.get(), "Olallieberry Bush");
        add(CMBlocks.ACEROLA_CHERRY_BUSH.get(), "Acerola Cherry Bush");
        add(CMBlocks.BARBERRY_BUSH.get(), "Barberry Bush");
        add(CMBlocks.BAYBERRY_BUSH.get(), "Bayberry Bush");
        add(CMBlocks.GOGI_BERRY_BUSH.get(), "Gogi Berry Bush");

        add(CMItems.MASON_JAR.get(), "Mason Jar");

        add(CMBlocks.SUGAR_BLOCK.get(), "Sugar Block");
        add(CMBlocks.SUGAR_CANE_BLOCK.get(), "Sugar Cane Block");

        add(CMBlocks.LAVA_SPONGE.get(), "Lava Sponge");
        add(CMBlocks.WET_LAVA_SPONGE.get(), "Saturated Lava Sponge");

        add(CMBlocks.SKINNY_SLANTED_BRICKS.get(), "Skinny Slanted Bricks");
        add(CMBlocks.SLANTED_BRICKS.get(), "Slanted Bricks");
        add(CMBlocks.SKINNY_BRICKS.get(), "Skinny Bricks");
        add(CMBlocks.CIRCULAR_BRICKS.get(), "Circular Bricks");
        add(CMBlocks.CRACKED_BRICKS.get(), "Cracked Bricks");
        add(CMBlocks.ENCASED_BRICKS.get(), "Encased Bricks");
        add(CMBlocks.MOSAIC_BRICKS.get(), "Mosaic Bricks");
        add(CMBlocks.ORNATE_BRICKS.get(), "Ornate Bricks");
        add(CMBlocks.ROAD_BRICKS.get(), "Road Bricks");
        add(CMBlocks.SOLID_BRICKS.get(), "Solid Bricks");
        add(CMBlocks.WEAVER_BRICKS.get(), "Weaver Bricks");

        add(CMBlocks.BLACK_REDSTONE_LAMP.get(), "Black Redstone Lamp");
        add(CMBlocks.BLUE_REDSTONE_LAMP.get(), "Blue Redstone Lamp");
        add(CMBlocks.BROWN_REDSTONE_LAMP.get(), "Brown Redstone Lamp");
        add(CMBlocks.CYAN_REDSTONE_LAMP.get(), "Cyan Redstone Lamp");
        add(CMBlocks.GRAY_REDSTONE_LAMP.get(), "Gray Redstone Lamp");
        add(CMBlocks.GREEN_REDSTONE_LAMP.get(), "Green Redstone Lamp");
        add(CMBlocks.LIGHT_BLUE_REDSTONE_LAMP.get(), "Light Blue Redstone Lamp");
        add(CMBlocks.LIGHT_GRAY_REDSTONE_LAMP.get(), "Light Gray Redstone Lamp");
        add(CMBlocks.LIME_REDSTONE_LAMP.get(), "Lime Redstone Lamp");
        add(CMBlocks.MAGENTA_REDSTONE_LAMP.get(), "Magenta Redstone Lamp");
        add(CMBlocks.ORANGE_REDSTONE_LAMP.get(), "Orange Redstone Lamp");
        add(CMBlocks.PINK_REDSTONE_LAMP.get(), "Pink Redstone Lamp");
        add(CMBlocks.PURPLE_REDSTONE_LAMP.get(), "Purple Redstone Lamp");
        add(CMBlocks.RED_REDSTONE_LAMP.get(), "Red Redstone Lamp");
        add(CMBlocks.WHITE_REDSTONE_LAMP.get(), "White Redstone Lamp");
        add(CMBlocks.YELLOW_REDSTONE_LAMP.get(), "Yellow Redstone Lamp");

        add("itemGroup.chrispymod", "Chrispy Mod");

        add(CMBlocks.ALLOY_FURNACE.get(), "Alloy Furnace");
        add("container.chrispymod.alloy_furnace", "Alloy Furnace");
        add(CMBlocks.JAM_AND_JELLY_MAKER.get(), "Jam and Jelly Maker");
        add("container.chrispymod.jam_and_jelly_maker", "Jam and Jelly Maker");
    }
}